### ISSUE TITLE
iqiyi parse failed since 2016.6.21

### ISSUE THREAD

**Issue by wnpllrzodiac** [soimort/you-get#1219] opened 2016-06-22 08:23 UTC
will always get a wrong sample clip

site: 爱奇艺 (Iqiyi)
title: 广告宣传片
streams: # Available quality and codecs
[ DEFAULT ]

**Comment by soimort** [comment] 2016-06-22 11:10
Duplicate of #1211.

**Closed** 2016-06-22 11:09 UTC
