### ISSUE TITLE
[youku]不能下载完整的视频

### ISSUE THREAD

**Issue by sosmygirl** [soimort/you-get#1265] opened 2016-07-09 05:16 UTC
Please make sure these boxes are checked before submitting your issue – thank you!

- [] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

C:\Users\lee>you-get --debug   http://v.youku.com/v_show/id_XMTYzMDkxMDU0NA==.html?from=y1.3-idx-beta-1519-23042.223465.1-1
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTYzMDkxMDU0NA==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMTYzMDkxMDU0NA==&ct=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/446804100517612ad629d_00/st/flv/fileid/0300801B005779F4820AF236EB4FEBAC050862-AA98-FED7-4228-A6A3C9B38671?yxon=1&ep=diaSEkmJV84A4CLYjj8bNnjkdn5bXP4J9h%2BNgdMQALshT%2B%2B27zrZxZ3BOP1BEIxrdlRzYpqCq9XnYkYWYYEyoGAQqTvcPvrk%2FPLr5dxVtZNzb2s1esvQtVScQjP1&K=286ac9fedb4c8c953412aac7&token=2134&oip=3657879744&ev=1&ctype=12
** you-get: [Error] HTTP Error 404: Not Found **
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/446804100517612ad629d_00/st/flv/fileid/03000113005779F0FF0AF236EB4FEBAC050862-AA98-FED7-4228-A6A3C9B38671?yxon=1&ep=diaSEkmJV84A4CLYjj8bNnjkdn5bXP4J9h%2BFgNNhALshT%2B%2B27z6nsZ3BOP1BEIxrdlRzYpqCq9XnYkYWYYEyoGAQqTvcPvrk%2FPLr5dxVtZNzb2s1esvQtVScQjP1&K=8d78848e4b93f11b282b8e7c&token=2134&oip=3657879744&ev=1&ctype=12
[DEBUG] get_content: http://k.youku.com/player/getFlvPath/sid/446804100517612ad629d_00/st/flv/fileid/03000113015779F0FF0AF236EB4FEBAC050862-AA98-FED7-4228-A6A3C9B38671?yxon=1&ep=diaSEkmJV84A4CLYjj8bNnjkdn5bXP4J9h%2BFgNNhALohT%2B%2B27z6nsZ3BOP1BEIxrdlRzYpqCq9XnYkYWYYEyoGAQqTvcPvrk%2FPLr5dxVtZNzb2s1esvQtVScQjP1&K=e55f86a6961d2ca6282b8e7c&token=2134&oip=3657879744&ev=1&ctype=12
site:                优酷 (Youku)
title:               任意依恋 02
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          698.9 MiB (732865343 bytes)
    # download-with: you-get --format=hd2 [URL]

Downloading 任意依恋 02.flv ...
 0.0% (  0.2/698.9MB) ├─────────────────────────────────────────┤[1/2]  466 k 0.1% (  0.5/698.9MB) ├─────────────────────────────────────────┤[1/2]    2 M 0.1% (  0.8/698.9MB) ├─────────────────────────────────────────┤[1/2]    5 M 0.1% (  1.0/698.9MB) ├─────────────────────────────────────────┤[1/2]    5 M 0.2% (  1.2/698.9MB) ├─────────────────────────────────────────┤[1/2]   11 M 0.2% (  1.5/698.9MB) ├─────────────────────────────────────────┤[1/2]    6 M 0.3% (  1.8/698.9MB) ├─────────────────────────────────────────┤[1/2]   10 M 0.3% (  2.0/698.9MB) ├─────────────────────────────────────────┤[1/2]   12 M 0.3% (  2.2/698.9MB) ├─────────────────────────────────────────┤[1/2]   10 M 0.4% (  2.5/698.9MB) ├─────────────────────────────────────────┤[1/2]   12 M 0.4% (  2.8/698.9MB) ├─────────────────────────────────────────┤[1/2]    3 M 0.4% (  3.0/698.9MB) ├─────────────────────────────────────────┤[1/2]   28 M 0.5% (  3.2/698.9MB) ├─────────────────────────────────────────┤[1/2]   19 M 0.5% (  3.5/698.9MB) ├─────────────────────────────────────────┤[1/2]   17 M 0.5% (  3.8/698.9MB) ├─────────────────────────────────────────┤[1/2]   17 M 0.6% (  4.0/698.9MB) ├─────────────────────────────────────────┤[1/2]   62 M 0.6% (  4.2/698.9MB) ├─────────────────────────────────────────┤[1/2]   12 M 0.6% (  4.5/698.9MB) ├─────────────────────────────────────────┤[1/2]   12 M 0.7% (  4.8/698.9MB) ├─────────────────────────────────────────┤[1/2]   10 M 0.7% (  5.0/698.9MB) ├─────────────────────────────────────────┤[1/2]   11 M 0.8% (  5.2/698.9MB) ├─────────────────────────────────────────┤[1/2]    3 M 0.8% (  5.5/698.9MB) ├─────────────────────────────────────────┤[1/2]   50 M 0.8% (  5.8/698.9MB) ├─────────────────────────────────────────┤[1/2]   83 M 0.9% (  6.0/698.9MB) ├─────────────────────────────────────────┤[1/2]  125 M 0.9% (  6.2/698.9MB) ├─────────────────────────────────────────┤[1/2]   12 M 0.9% (  6.5/698.9MB) ├─────────────────────────────────────────┤[1/2]   10 M 1.0% (  6.8/698.9MB) ├█────────────────────────────────────────┤[1/2]   11 M 1.0% (  7.0/698.9MB) ├█────────────────────────────────────────┤[1/2]   11 M 1.0% (  7.2/698.9MB) ├█────────────────────────────────────────┤[1/2]    9 M 1.1% (  7.5/698.9MB) ├█────────────────────────────────────────┤[1/2]    3 M 1.1% (  7.8/698.9MB) ├█────────────────────────────────────────┤[1/2]  125 M 1.1% (  8.0/698.9MB) ├█────────────────────────────────────────┤[1/2]   14 M 1.2% (  8.2/698.9MB) ├█────────────────────────────────────────┤[1/2]    8 M 1.2% (  8.5/698.9MB) ├█────────────────────────────────────────┤[1/2]    8 M 1.3% (  ‘’‘’
‘’‘’‘’‘
’‘’‘’‘’‘’
78.7/698.9MB) ├█████────────────────────────────────────┤[2/2]   10 M11.3% ( 79.0/698.9MB) ├█████────────────────────────────────────┤[2/2]   10 M11.3% ( 79.2/698.9MB) ├█████────────────────────────────────────┤[2/2]    9 M11.3% ( 79.3/698.9MB) ├█████────────────────────────────────────┤[2/2]   18 MB/s
Merging video parts... Merged into 任意依恋 02.mp4
```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by soimort** [comment] 2016-07-09 20:45
```
you-get: [Error] HTTP Error 404: Not Found
```

May be a duplicate of #1249 .

**Closed** 2016-08-03 12:48 UTC
Labels: duplicate
