### ISSUE TITLE
error when trying to watch livestream videos on douyu.com

### ISSUE THREAD

**Issue by pthreadself** [soimort/you-get#1399] opened 2016-09-12 09:58 UTC
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
you-get --debug -u https://www.douyu.com/534740
[DEBUG] get_content: http://www.douyu.com/534740
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=534740
Site:       douyu.com
Title:      【六神】救人一命，胜造七级浮屠！
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

Real URL:
['http://hdl3.douyucdn.cn/live/534740rzp3e4UL6z.flv?wsAuth=8c2f3f6dd1aefb19b5b2fb9908e170c3&token=web-douyu-0-534740-f4bd6cee4cf9698b8c8ff146749152b8&logo=0&expire=0&did=7F62021986514543A599647F1BEBD029']

you-get: version 0.4.536, a tiny downloader that scrapes the web.
you-get: ['https://www.douyu.com/534740']
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1331, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1244, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1060, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1324, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/douyutv.py", line 52, in douyutv_download
    download_url_ffmpeg(real_url, title, 'flv', None, output_dir = output_dir, merge = merge)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 908, in download_url_ffmpeg
    if params.get("-y",False): #None or unset ->False
AttributeError: 'NoneType' object has no attribute 'get'
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by soimort** [comment] 2016-09-13 09:11
Duplicate of #1348. See also https://github.com/soimort/you-get/issues/1336#issuecomment-239614272. This part was not correctly implemented -- sadly (as of now) no one cares to fix it.

**Closed by soimort** 2016-09-13 09:11 UTC
Labels: duplicate
