### ISSUE TITLE
网易云音乐下载不了

### ISSUE THREAD

**Issue by happyhuaer** [soimort/you-get#2003] opened 2017-05-23 08:43 UTC
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```[DEBUG] get_content: http://music.163.com/api/song/detail/?id=306680&ids=[306680]&csrf_token=
you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/#/song?id=306680']
Traceback (most recent call last):
  File "C:\Users\zxf\AppData\Local\Programs\Python\Python36-32\Scripts\you-get-script.py", line 11, in <module>
    load_entry_point('you-get==0.4.750', 'console_scripts', 'you-get')()
  File "C:\Users\zxf\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\__main__.py", line 92, in main
  File "C:\Users\zxf\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\common.py", line 1444, in main
  File "C:\Users\zxf\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\common.py", line 1355, in script_main
  File "C:\Users\zxf\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\common.py", line 1157, in download_main
  File "C:\Users\zxf\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\common.py", line 1437, in any_download
  File "C:\Users\zxf\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\extractors\netease.py", line 133, in netease_download
  File "C:\Users\zxf\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\extractors\netease.py", line 70, in netease_cloud_music_download
  File "C:\Users\zxf\AppData\Local\Programs\Python\Python36-32\lib\site-packages\you_get-0.4.750-py3.6.egg\you_get\extractors\netease.py", line 110, in netease_song_download
AttributeError: 'NoneType' object has no attribute 'split'
[在这里粘贴完整日志]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by rosynirvana** [comment] 2017-05-23 11:07
Duplicate of #1990

**Comment by dAxIOnG8** [comment] 2017-05-27 03:35
(py35) C:\Users\shu>you-get --debug http://music.163.com/#/playlist?id=71092210
[DEBUG] get_content: http://music.163.com/api/playlist/detail?id=71092210&csrf_token=
Skipping ./调调情，睡睡觉\cover.jpg: file already exists

you-get: version 0.4.750, a tiny downloader that scrapes the web.
you-get: ['http://music.163.com/#/playlist?id=71092210']
Traceback (most recent call last):
  File "c:\anaconda3\envs\py35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\anaconda3\envs\py35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Anaconda3\envs\py35\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\anaconda3\envs\py35\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\anaconda3\envs\py35\lib\site-packages\you_get\common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\anaconda3\envs\py35\lib\site-packages\you_get\common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\anaconda3\envs\py35\lib\site-packages\you_get\common.py", line 1157, in download_main
    download(url, **kwargs)
  File "c:\anaconda3\envs\py35\lib\site-packages\you_get\common.py", line 1437, in any_download
    m.download(url, **kwargs)
  File "c:\anaconda3\envs\py35\lib\site-packages\you_get\extractors\netease.py", line 133, in netease_download
    netease_cloud_music_download(url, output_dir, merge, info_only, **kwargs)
  File "c:\anaconda3\envs\py35\lib\site-packages\you_get\extractors\netease.py", line 61, in netease_cloud_music_download
    netease_song_download(i, output_dir=new_dir, info_only=info_only, playlist_prefix=playlist_prefix)
  File "c:\anaconda3\envs\py35\lib\site-packages\you_get\extractors\netease.py", line 110, in netease_song_download
    songNet = 'p' + song['mp3Url'].split('/')[2][1:]
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by rosynirvana** [comment] 2017-07-15 21:35
in favor of #2074

**Closed by rosynirvana** 2017-07-15 21:35 UTC
