### ISSUE TITLE
腾讯视频下载只能下载5分钟的短片

### ISSUE THREAD

**Issue by bonecto** [soimort/you-get#1420] opened 2016-09-26 13:18 UTC
you-get -di http://101.227.216.147/vlive.qqvideo.tc.qq.com//o0020u77uly.p203.1.mp4?vkey=D1AF396B8F897FE54AEBA21F07FD9BC1C474D70B8741B3AF0273B57D264620F48D1EE8E4CA0ACD5EA016BF9BB4464DE573CCB3F4A4DF1953312764841B0125E17D6F18E5B03DC0BDCB018514C6851DF4AF08CC5F95EC3613
Site:       227.216.149
Title:      o0020u77uly.p203.1
Type:       Unknown type (mp4?vkey=d1af396b8f897fe54aeba21f07fd9bc1c474d70b8741b3af0273b57d264620f48d1ee8e4ca0acd5ea016bf9bb4464de573ccb3f4a4df1953312764841b0125e17d6f18e5b03dc0bdcb018514c6851df4af08cc5f95ec3613&locid=588419c3-cac9-4554-92c9-ee50dc069e3d&size=11545359&ocid=290133420)
Size:       11.01 MiB (11545359 Bytes)

不能下载完整的电视集，下载的只有5分钟
测试地址：http://101.227.216.147/vlive.qqvideo.tc.qq.com

**Comment by soimort** [comment] 2016-10-19 19:00
Duplicate of #1326.

**Closed by soimort** 2016-10-19 19:00 UTC
Labels: duplicate
