### ISSUE TITLE
Add custom save file name argument

### ISSUE THREAD

**Issue by lucifekit** [soimort/you-get#592] opened 2015-08-11 09:47 UTC
I know the python file can automatically read the video title and save it as file name, but i want to use my file name when the file name is in chinese language, please add the custom file name argument please.

**Comment by jackyzy823** [comment] 2015-08-12 04:59
In my view,you can rename the file after download.

**Comment by lucifekit** [comment] 2015-08-12 05:55
I use on windows, sometime i use on some chinese site, the video title is in chinese and it give error. Beside, if i use batch to download entire playlist when you-get does not support, i need  a custom filename argument. By the way, i modify the source myself but i think there is other people would like it become offical. By the way again, great project sir,i love it so much

**Comment by jackyzy823** [comment] 2015-08-12 07:31
Why not make a pull request of your modification? Patches are welcomed!

**Comment by lucifekit** [comment] 2015-08-12 08:00
Because i'm not good at python, so my modifier maybe not in well formatted, it can only work in my position, and can make other code go wrong :(, and beside i do not know how to make a pull request.

My change is : 
A. In common.py
1. Add this to about line 828, to add extra argument,
--debug                             Show traceback on KeyboardInterrupt.
-->
         --debug                             Show traceback on KeyboardInterrupt.
         -s | --save-file-name          Save file name
2. Change the short_opts line to add the short argument -s : 
short_opts = 'Vhfiuc:nF:o:p:x:y:'
-->
short_opts = 'Vhfiuc:nF:o:p:x:y:s:'
3. Add the global save_file_name variable to line 850
global cookies_txt
-->
global cookies_txt
global save_file_name
4. Set default value to it at line 861
traceback = False
-->
traceback = False
save_file_name = ''
5. Add -s to opt at about line 890
elif o in ('-o', '--output-dir'):
      output_dir = a
-->
elif o in ('-o', '--output-dir'):
            output_dir = a
 elif o in ('-s','--save-file-name'):
            save_file_name = a

6. Last, add save_file_name as argument to the download function at line 915
if stream_id:
            if not extractor_proxy:
                download_main(download, download_playlist, args, playlist, stream_id=stream_id, output_dir=output_dir, merge=merge, info_only=info_only)
            else:
                download_main(download, download_playlist, args, playlist, stream_id=stream_id, extractor_proxy=extractor_proxy, output_dir=output_dir, merge=merge, info_only=info_only)
        else:
            if not extractor_proxy:
                download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
            else:
                download_main(download, download_playlist, args, playlist, extractor_proxy=extractor_proxy, output_dir=output_dir, merge=merge, info_only=info_only)

-->

if stream_id:
            if not extractor_proxy:
                download_main(download, download_playlist, args, playlist, stream_id=stream_id, output_dir=output_dir, merge=merge, info_only=info_only,save_file_name=save_file_name)
            else:
                download_main(download, download_playlist, args, playlist, stream_id=stream_id, extractor_proxy=extractor_proxy, output_dir=output_dir, merge=merge, info_only=info_only,save_file_name=save_file_name)
        else:
            if not extractor_proxy:
                download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only,save_file_name=save_file_name)
            else:
                download_main(download, download_playlist, args, playlist, extractor_proxy=extractor_proxy, output_dir=output_dir, merge=merge, info_only=info_only,save_file_name=save_file_name)


B. And i use the save_file_name in the extractor iqiyi.py
1. Line 104 add the save_file_name argument
def iqiyi_download(url, output_dir = '.', merge = True, info_only = False):
-->
def iqiyi_download(url, output_dir = '.', merge = True, info_only = False,save_file_name=''):

2. About line 163, add this line so if we specific the save_file_name variable the title will be what we want

print_info(site_info, title, 'flv', size)
-->
if not save_file_name=='':
        title = save_file_name
print_info(site_info, title, 'flv', size)

**Comment by soimort** [comment] 2015-08-30 12:00
Duplicate of #425.

**Closed** 2015-10-30 21:31 UTC
Labels: duplicate, enhancement
