### ISSUE TITLE
PPTV聚力(http://www.pptv.com),土豆(http://www.tudou.com) 视频解析问题

### ISSUE THREAD

**Issue by gasry1989** [soimort/you-get#1988] opened 2017-05-20 11:06 UTC
1.PPTV问题描述：
C:\Users\Administrator\Downloads\you-get-develop>python you-get --debug "http://v.pptv.com/show/xx73dNxCsvBT0Tk.html?rcc_src=L1"
you-get: version 0.4.715, a tiny downloader that scrapes the web.
you-get: ['http://v.pptv.com/show/xx73dNxCsvBT0Tk.html?rcc_src=L1']
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "C:\Users\Administrator\Downloads\you-get-develop/src\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "C:\Users\Administrator\Downloads\you-get-develop/src\you_get\common.py", line 1444, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "C:\Users\Administrator\Downloads\you-get-develop/src\you_get\common.py", line 1355, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "C:\Users\Administrator\Downloads\you-get-develop/src\you_get\common.py",
 line 1157, in download_main
    download(url, **kwargs)
  File "C:\Users\Administrator\Downloads\you-get-develop/src\you_get\common.py",
 line 1437, in any_download
    m.download(url, **kwargs)
  File "C:\Users\Administrator\Downloads\you-get-develop/src\you_get\extractors\pptv.py", line 146, in pptv_download
    assert re.match(r'http://v.pptv.com/show/(\w+)\.html$', url)
AssertionError

2.土豆问题描述
C:\Users\Administrator\Downloads\you-get-develop>python you-get --debug "http://video.tudou.com/v/XMjYxODEzNjQ0MA==.html?t=1&recoid=18340949209759593361&itemid=17005616193154789098&spm=a2h28.8313461.sec1.dimg_5_8"
[DEBUG] get_content: http://video.tudou.com/v/XMjYxODEzNjQ0MA==.html?t=1&recoid=18340949209759593361&itemid=17005616193154789098&spm=a2h28.8313461.sec1.dimg_5_8

[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjYxODEzNjQ0MA==&ct=10
[DEBUG] get_content: http://play.youku.com/play/get.json?vid=XMjYxODEzNjQ0MA==&ct=12
you-get: [Failed] 抱歉，因版权原因无法观看此视频！

**Comment by soimort** [comment] 2017-05-20 20:19
Duplicate of #1935 and #1957.

**Closed by soimort** 2017-05-20 20:19 UTC
Labels: confirmed, duplicate
