### ISSUE TITLE
bilibili有些番剧解析不了了

### ISSUE THREAD

**Issue by lioliy** [soimort/you-get#1460] opened 2016-10-16 14:32 UTC
bilibili you-get -di http://bangumi.bilibili.com/anime/v/96394
[DEBUG] get_content: http://bangumi.bilibili.com/anime/v/96394
[DEBUG] get_content: http://www.bilibili.com/video/av6666942/
you-get: version 0.4.555, a tiny downloader that scrapes the web.
...
AssertionError

**Comment by soimort** [comment] 2016-10-16 16:00
Duplicate of #1436.

**Closed** 2016-10-16 16:00 UTC
Labels: duplicate
