### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2

### ISSUE THREAD

**Issue by BerndSchneider** [soimort/you-get#833] opened 2015-12-26 21:41 UTC
Hello,

I get an UnicodeEncodeError on LeTV. Here is the debug output:

`you-get -d --format 720p http://www.letv.com/ptv/vplay/24135692.html
Site:       LeTV.com
you-get: version 0.4.217, a tiny downloader that scrapes the web.
you-get: ['http://www.letv.com/ptv/vplay/24135692.html']
Title:      Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.2/site-packages/you_get-0.4.217-py3.2.egg/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/root/.local/lib/python3.2/site-packages/you_get-0.4.217-py3.2.egg/you_get/common.py", line 1229, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/root/.local/lib/python3.2/site-packages/you_get-0.4.217-py3.2.egg/you_get/common.py", line 1145, in script_main
    download_main(download, download_playlist, args, playlist, stream_id=stream_id, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "/root/.local/lib/python3.2/site-packages/you_get-0.4.217-py3.2.egg/you_get/common.py", line 1003, in download_main
    download(url, **kwargs)
  File "/root/.local/lib/python3.2/site-packages/you_get-0.4.217-py3.2.egg/you_get/common.py", line 1222, in any_download
    m.download(url, **kwargs)
  File "/root/.local/lib/python3.2/site-packages/you_get-0.4.217-py3.2.egg/you_get/extractors/letv.py", line 139, in letv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, info_only=info_only,**kwargs)
  File "/root/.local/lib/python3.2/site-packages/you_get-0.4.217-py3.2.egg/you_get/extractors/letv.py", line 96, in letv_download_by_vid
    print_info(site_info, title, ext, size)
  File "/root/.local/lib/python3.2/site-packages/you_get-0.4.217-py3.2.egg/you_get/common.py", line 938, in print_info
    print("Title:     ", unescape_html(tr(title)))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-2: ordinal not in range(128)`

Thanks

**Comment by soimort** [comment] 2015-12-29 15:26
Duplicate of #791.

Solution: [Set your locale to UTF-8](https://www.google.com/search?q=set+locale+to+UTF-8).

**Closed by soimort** 2015-12-29 15:26 UTC
