### ISSUE TITLE
DouyuTV下载（录制）失效

### ISSUE THREAD

**Issue by airzwx** [soimort/you-get#1299] opened 2016-07-22 08:45 UTC
最近在用you-get录制斗鱼直播，一直正常使用，大约在北京时间7月21日晚，工具里使用的斗鱼API修改了认证方式，工具里现有的斗鱼API调用失效，返回 错误1002：api身份信息错误

> {"error":1002,"data":"api\u8eab\u4efd\u4fe1\u606f\u9519\u8bef"}

测试链接：
http://www.douyu.com/17732

使用环境：Windows XP（低配下载机） + Python 3.4.4 以及 CentOS 6.8 + Python 3.4.5

`you-get -d http://www.douyu.com/17732`
> you-get: version 0.4.486, a tiny downloader that scrapes the web.
> you-get: ['http://www.douyu.com/17732']
> Traceback (most recent call last):
>   File "c:\program files\python34\lib\runpy.py", line 170, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\program files\python34\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Program Files\Python34\Scripts\you-get.exe\__main__.py", line 9, in <module>
>   File "c:\program files\python34\lib\site-packages\you_get\__main__.py", line 92, in main
>     main(**kwargs)
>   File "c:\program files\python34\lib\site-packages\you_get\common.py", line 1328, in main
>     script_main('you-get', any_download, any_download_playlist, **kwargs)
>   File "c:\program files\python34\lib\site-packages\you_get\common.py", line 1241, in script_main
>     download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
>   File "c:\program files\python34\lib\site-packages\you_get\common.py", line 1060, in download_main
>     download(url, **kwargs)
>   File "c:\program files\python34\lib\site-packages\you_get\common.py", line 1321, in any_download
>     m.download(url, **kwargs)
>   File "c:\program files\python34\lib\site-packages\you_get\extractors\douyutv.py", line 19, in douyutv_download
>     server_status = data.get('error',0)
> AttributeError: 'str' object has no attribute 'get'

使用Fiddler抓包目前Android版斗鱼客户端，发现其使用的API地址已变更，形式如下

> http://capi.douyucdn.cn/api/v1/room/{Room_ID}?aid=android1&client_sys=android&ne=1&support_pwd=1&time={int(time.time())}&auth={Auth}

或

> http://capi.douyucdn.cn/api/v1/room/{Room_ID}?aid=android1&cdn=ws&client_sys=android&ne=1&support_pwd=1&time={int(time.time())}&auth={Auth}

与工具里使用的API相比，差异部分有：使用的API域名由www.douyu.com变为capi.douyucdn.cn，aid参数由android变为android1，新增了ne和support_pwd参数，偶尔会指定cdn参数，auth参数计算方法未知，使用现有计算方法计算从"/room"开始到"auth"前字符串无法得到与抓包结果相同的auth

**Comment by lamlam123tld3** [comment] 2016-07-22 10:22
全挂了吧 只剩下POST的lapi

**Comment by ERioK** [comment] 2016-07-24 11:05
用ffdec从内存里得到了解密后的swf文件..里面应该有sign的算法..as代码看不懂，希望有懂的看一下

**Comment by cjztool** [comment] 2016-07-26 08:08
![default](https://cloud.githubusercontent.com/assets/3993323/17130350/b542488a-534a-11e6-910c-182960638234.png)

汇编斗鱼Android2_2_8_2的 libdanmu.so

如果能看明白native_makeurl 这个函数,斗鱼的播放就能搞定了. 亲们,加油啊 我只能帮大家到这了

**Comment by cnbeining** [comment] 2016-07-28 20:23
@ERioK 我的ffdec的内存dump功能不知道为什么炸了。。。。。。

**Comment by zhangn1985** [comment] 2016-07-28 23:25
用html5可以下载20～30分钟

**Comment by cnbeining** [comment] 2016-07-29 01:02
@cjztool 这是IDA么。。。？

然而如果是C 那么运气就很小了啊。

**Comment by cnbeining** [comment] 2016-07-29 01:03
@zhangn1985 HTML5的API？哪里？

**Comment by zhangn1985** [comment] 2016-07-29 01:37
http://m.douyu.com/html5/live?roomId={}

**Comment by yan12125** [comment] 2016-07-29 02:12
> 然而如果是C 那么运气就很小了啊。

Call qemu (X)

**Comment by cnbeining** [comment] 2016-07-29 02:12
@yan12125 Cmodule跑不动他的.so 有可能是因为我是64位吧。

**Comment by steven7851** [comment] 2016-07-29 05:12
试写了一个 you-get 的 extractors
不知道为什么一直返回 403
大神们帮帮忙
```python
#!/usr/bin/env python

__all__ = ['douyutv_download']

from ..common import *
import json
import hashlib
import time
import random
import string
import requests

def douyutv_download(url, output_dir = '.', merge = True, info_only = False, **kwargs):
    room_id = url[url.rfind('/')+1:]

    json_request_url = "http://m.douyu.com/html5/live?roomId=%s" % room_id
    content = get_html(json_request_url)
    data = json.loads(content)['data']
    server_status = data.get('error',0)
    if server_status is not 0:
        raise ValueError("Server returned error:%s" % server_status)

    title = data.get('room_name')
    show_status = data.get('show_status')
    if show_status is not "1":
        raise ValueError("The live stream is not online! (Errno:%s)" % server_status)

    tt = int(time.time() / 60)
    did = ''.join([random.choice(string.ascii_uppercase + string.digits) for n in range(32)])
    sign = hashlib.md5((room_id + did + 'A12Svb&%1UUmf@hC' + "%d" % tt).encode("utf-8")).hexdigest()
    json_request_url = "http://www.douyu.com/lapi/live/getPlay/%s" % room_id

    payload = {'cdn': 'ws', 'rate': '0', 'tt': tt, 'did': did, 'sign': sign}
    r = requests.post(json_request_url, data=payload)
    content = r.json()
    data = content['data']

    server_status = data.get('error',0)
    if server_status is not 0:
        raise ValueError("Server returned error:%s" % server_status)

    real_url = data.get('rtmp_url')+'/'+data.get('rtmp_live')

    print_info(site_info, title, 'flv', float('inf'))
    if not info_only:
        download_urls([real_url], title, 'flv', None, output_dir, merge = merge)

site_info = "douyu.com"
download = douyutv_download
download_playlist = playlist_not_supported('douyu')

```

**Comment by cnbeining** [comment] 2016-07-29 05:14
```
    sign = hashlib.md5((room_id + did + 'A12Svb&%1UUmf@hC' + "%d" % tt).encode("utf-8")).hexdigest()
```

这段是。。。？

**Comment by steven7851** [comment] 2016-07-29 05:15
@cnbeining 
从网页的swf解密出的lapi算法

**Comment by cnbeining** [comment] 2016-07-29 05:16
@steven7851 用ffdec弄出来的swf？

**Comment by steven7851** [comment] 2016-07-29 05:17
@cnbeining 
是的，在#1235 @hellofwy 帮忙的

**Comment by cnbeining** [comment] 2016-07-29 05:29
你提个PR吧。我test通过。

```
#!/usr/bin/env python

__all__ = ['douyutv_download']

from ..common import *
import json
import hashlib
import time
import random
import string
import requests

def douyutv_download(url, output_dir = '.', merge = True, info_only = False, **kwargs):
    room_id = url[url.rfind('/')+1:]

    json_request_url = "http://m.douyu.com/html5/live?roomId=%s" % room_id
    content = get_html(json_request_url)
    data = json.loads(content)['data']
    server_status = data.get('error',0)
    if server_status is not 0:
        raise ValueError("Server returned error:%s" % server_status)

    title = data.get('room_name')
    show_status = data.get('show_status')
    if show_status is not "1":
        raise ValueError("The live stream is not online! (Errno:%s)" % server_status)

    tt = int(time.time() / 60)
    did = ''.join([random.choice(string.ascii_uppercase + string.digits) for n in range(32)])
    sign = hashlib.md5((room_id + did + 'A12Svb&%1UUmf@hC' + "%d" % tt).encode("utf-8")).hexdigest()
    json_request_url = "http://www.douyu.com/lapi/live/getPlay/%s" % room_id

    payload = {'cdn': 'ws', 'rate': '0', 'tt': tt, 'did': did, 'sign': sign}
    r = requests.post(json_request_url, data=payload)
    content = r.json()
    data = content['data']

    server_status = data.get('error',0)
    if server_status is not 0:
        raise ValueError("Server returned error:%s" % server_status)

    real_url = data.get('rtmp_url')+'/'+data.get('rtmp_live')

    print_info(site_info, title, 'flv', float('inf'))
    if not info_only:
        print(real_url)
        download_url_ffmpeg(real_url, title, 'flv', None, output_dir, merge = merge)

site_info = "douyu.com"
download = douyutv_download
download_playlist = playlist_not_supported('douyu')
```

**Comment by 5ace** [comment] 2016-08-01 07:29
@steven7851 能简单说一下怎么找到的么，我ie打开斗鱼，ffdec 怎么找不到。稍微指点下

**Comment by xingchch** [comment] 2016-08-01 08:52
python3 ./you-get -d -i http://www.douyu.com/690400
[DEBUG] get_content: http://www.douyu.com/690400
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=690400
you-get: version 0.4.486, a tiny downloader that scrapes the web.
you-get: ['http://www.douyu.com/690400']
Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/xingchch/git/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/xingchch/git/you-get/src/you_get/common.py", line 1331, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/xingchch/git/you-get/src/you_get/common.py", line 1244, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/xingchch/git/you-get/src/you_get/common.py", line 1060, in download_main
    download(url, **kwargs)
  File "/home/xingchch/git/you-get/src/you_get/common.py", line 1324, in any_download
    m.download(url, **kwargs)
  File "/home/xingchch/git/you-get/src/you_get/extractors/douyutv.py", line 39, in douyutv_download
    with urllib.request.urlopen(req) as response:
  File "/usr/lib/python3.4/urllib/request.py", line 161, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.4/urllib/request.py", line 469, in open
    response = meth(req, response)
  File "/usr/lib/python3.4/urllib/request.py", line 579, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.4/urllib/request.py", line 507, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 441, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.4/urllib/request.py", line 587, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 503: Service Unavailable

**Comment by steven7851** [comment] 2016-08-02 12:31
@xingchch 
The extractor is working well here, maybe is network problem or else?

**Comment by steven7851** [comment] 2016-08-02 12:46
@5ace 先开斗鱼载入好页面后, Tools 裡有个 Search SWFs in memory, 点选你的browser, 右边就有SWF每个都打开看看, 有个AS很多的就是core.swf了

**Comment by xingchch** [comment] 2016-08-03 02:38
一．　无法下载，只有链接出来了．
Site:       douyu.com
Title:      打着打着又睡着了
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

Real URL:
['http://hdl3.douyucdn.cn/live/508606rL2xQk3348.flv?wsAuth=3a24bea6c40b4d7ae947c93af55f3063&token=web-0-508606-b8d676dc1dd5099f92eeb94f5b12adb0&logo=0&expire=0']

you-get: version 0.4.486, a tiny downloader that scrapes the web.
you-get: ['http://www.douyu.com/508606']
Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/xingchch/git/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/xingchch/git/you-get/src/you_get/common.py", line 1332, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/xingchch/git/you-get/src/you_get/common.py", line 1245, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/xingchch/git/you-get/src/you_get/common.py", line 1061, in download_main
    download(url, **kwargs)
  File "/home/xingchch/git/you-get/src/you_get/common.py", line 1325, in any_download
    m.download(url, **kwargs)
  File "/home/xingchch/git/you-get/src/you_get/extractors/douyutv.py", line 55, in douyutv_download
    download_url_ffmpeg(real_url, title, 'flv', None, output_dir, merge = merge)
  File "/home/xingchch/git/you-get/src/you_get/common.py", line 908, in download_url_ffmpeg
    if params.get("-y",False): #None or unset ->False
AttributeError: 'NoneType' object has no attribute 'get'

二．链接放到浏览器中回车，可以ｄｏｗｎｌｏａｄ下来，但是把链接直接放到video标签中，却无法播放．这是为什么呢

**Comment by 5ace** [comment] 2016-08-03 02:39
@steven7851 多谢，找到一段代码
               StreamSignDataPtr = CModule.malloc(4);
               data_len = xx.sub_13(int(Param.RoomId),min,Util.getGuid(),StreamSignDataPtr);
               resData = CModule.read32(StreamSignDataPtr);
               signStr = CModule.readString(resData,data_len);
生成盐的，不知道对么，弱问一下，这个怎么看懂的，还是不用看懂有办法运行？

**Comment by cnbeining** [comment] 2016-08-03 02:42
@xingchch 

第一个问题：code有问题，等我细查。

第二个问题：HTML5不原生支持flv。

@5ace 你需要知道每个函数到底是怎么回事。

**Comment by steven7851** [comment] 2016-08-03 03:30
@xingchch @cnbeining 
line 52, None 换成 {} 就正常下载了，这是导致这问题的原因？
```python
        download_url_ffmpeg(real_url, title, 'flv', None, output_dir, merge = merge)
        download_url_ffmpeg(real_url, title, 'flv', {}, output_dir, merge = merge)
```

**Comment by 5ace** [comment] 2016-08-04 08:20
@cnbeining @steven7851 往里面看了一下，调用层次很多都是汇编，有什么么技巧么，还是只能读汇编。。 求指点

**Comment by cnbeining** [comment] 2016-08-04 08:21
@5ace 如果真是ASM那就很坑爹了。只能打断点或者翻内存了。

**Comment by nlimpid** [comment] 2016-08-04 14:08
https://github.com/steven7851/livestreamer/commit/6bbb6cf279096c6c8e90437e72494a663ef7b50e  这个commit提到了使用新的douyu api，我试了这个commit所在的分支是可以正常解析 douyu 的，你们要不看看？ @cnbeining @steven7851

**Comment by steven7851** [comment] 2016-08-04 22:29
@nlimpid 
It is the same with https://github.com/soimort/you-get/pull/1315.
Although it was merged into you-get, but it has some issue caused by ffmpeg processor.
(see my comment above)

**Comment by hellofwy** [comment] 2016-08-05 10:51
@cnbeining 我是直接读的ffdec反汇编出来的代码。如果可以打断点，或者准确的翻内存，倒是简单一些，但不知怎么弄。

**Comment by nopcnblog** [comment] 2016-08-05 12:39
@steven7851 请问A12Svb&%1UUmf@hC 这个值是怎么找到的，可以告诉方法吗？

**Comment by steven7851** [comment] 2016-08-05 20:13
是@hellofwy 帮忙找的，我自己试过了也是没有找到。。

**Comment by soimort** [comment] 2016-08-07 18:27
I could not reproduce the error with the latest `develop` branch. Anyone?

```
$ you-get -d http://www.douyu.com/17732  
[DEBUG] get_content: http://www.douyu.com/17732
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=17732
Site:       douyu.com
Title:      清晨醒脑！T-ara根本停不下来！
Type:       Flash video (video/x-flv)
Size:       inf MiB (inf Bytes)

Downloading streaming content with FFmpeg, press q to stop recording...
ffmpeg -y -re -i http://hdl3.douyucdn.cn/live/17732rtara.flv?wsAuth=6d95831ccebb2b3cd9b771f2c183b395&token=web-0-17732-c1b2b10fff3c6f93fa32eec9d98af367&logo=0&expire=0 -c copy -bsf:a aac_adtstoasc 清晨醒脑！T-ara根本停不下来！.flv
ffmpeg version 3.1.1 Copyright (c) 2000-2016 the FFmpeg developers
  built with gcc 6.1.1 (GCC) 20160707
  configuration: --prefix=/usr --disable-debug --disable-static --disable-stripping --enable-avisynth --enable-avresample --enable-fontconfig --enable-gmp --enable-gnutls --enable-gpl --enable-ladspa --enable-libass --enable-libbluray --enable-libfreetype --enable-libfribidi --enable-libgsm --enable-libiec61883 --enable-libmodplug --enable-libmp3lame --enable-libopencore_amrnb --enable-libopencore_amrwb --enable-libopenjpeg --enable-libopus --enable-libpulse --enable-libschroedinger --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libv4l2 --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx264 --enable-libx265 --enable-libxvid --enable-netcdf --enable-shared --enable-version3 --enable-x11grab
  libavutil      55. 28.100 / 55. 28.100
  libavcodec     57. 48.101 / 57. 48.101
  libavformat    57. 41.100 / 57. 41.100
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 47.100 /  6. 47.100
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
[flv @ 0x561fa30b2aa0] audio stream discovered after head already parsed
[flv @ 0x561fa30b2aa0] video stream discovered after head already parsed
Input #0, flv, from 'http://hdl3.douyucdn.cn/live/17732rtara.flv?wsAuth=6d95831ccebb2b3cd9b771f2c183b395&token=web-0-17732-c1b2b10fff3c6f93fa32eec9d98af367&logo=0&expire=0':
  Metadata:
    fileSize        : 0
    audiochannels   : 2
    encoder         : Open Broadcaster Software v0.657b
  Duration: 00:00:00.00, start: 0.008000, bitrate: N/A
    Stream #0:0: Audio: aac (LC), 48000 Hz, stereo, fltp
    Stream #0:1: Video: h264 (High), yuv420p(tv, smpte170m/bt709/iec61966-2-1), 1280x720, 25 fps, 25 tbr, 1k tbn, 50 tbc
[flv @ 0x561fa31e24e0] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
    Last message repeated 1 times
Output #0, flv, to '清晨醒脑！T-ara根本停不下来！.flv':
  Metadata:
    fileSize        : 0
    audiochannels   : 2
    encoder         : Lavf57.41.100
    Stream #0:0: Video: h264 ([7][0][0][0] / 0x0007), yuv420p(tv, smpte170m/bt709/iec61966-2-1), 1280x720, q=2-31, 25 fps, 25 tbr, 1k tbn, 1k tbc
    Stream #0:1: Audio: aac (LC) ([10][0][0][0] / 0x000A), 48000 Hz, stereo
Stream mapping:
  Stream #0:1 -> #0:0 (copy)
  Stream #0:0 -> #0:1 (copy)
Press [q] to stop, [?] for help
frame=   14 fps=0.0 q=-1.0 size=     237kB time=00:00:00.51 bitrate=3783.3kbits/s frame=   26 fps= 26 q=-1.0 size=     356kB time=00:00:01.04 bitrate=2787.2kbits/s frame=   39 fps= 26 q=-1.0 size=     496kB time=00:00:01.55 bitrate=2610.5kbits/s ^Cframe=   51 fps= 25 q=-1.0 Lsize=     628kB time=00:00:02.02 bitrate=2539.7kbits/s speed=1.01x    
```

@soimort-bot please test this: http://www.douyu.com/17732

**Comment by steven7851** [comment] 2016-08-08 03:24
@soimort There is no error on latest release. Thank you.

**Comment by hellofwy** [comment] 2016-08-08 03:42
除了html5，从《斗鱼第三方开放平台API文档v2.1》获取房间信息也是一种方法:
http://dev-bbs.douyutv.com/forum.php?mod=viewthread&tid=113

**Comment by daxiaxia** [comment] 2016-08-08 05:15
啥时候能修复啊 各位大大

**Comment by soimort** [comment] 2016-08-08 11:55
Closing, since @steven7851's PR #1315 has been merged.

Thanks to everyone who contributed to the discussion so far.

**Closed by soimort** 2016-08-08 11:55 UTC
Labels: confirmed, patches welcome

**Comment by 0x94** [comment] 2016-08-17 10:53
@steven7851 想请教 你拿出来keeplive的k加密方法了吗 我也用ffdec拿了swf 里面这个函数直接return '222222'

**Comment by yijunjun** [comment] 2017-05-12 03:45
@0x94 兄弟你搞定
··· shell
StreamSignDataPtr = CModule.malloc(4);
data_len = xx.sub_13(int(Param.RoomId),min,Util.getGuid(),StreamSignDataPtr);
resData = CModule.read32(StreamSignDataPtr);
signStr = CModule.readString(resData,data_len);
```
这段代码没有？
