### ISSUE TITLE
无法播放douyu.com

### ISSUE THREAD

**Issue by isbaseby** [soimort/you-get#1301] opened 2016-07-23 07:38 UTC
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ ] Your `you-get` is up-to-date.
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[PASTE IN ME]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [ ] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [ ] 您的`you-get`为最新版.
- [ ] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [ ] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [ ] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
➜  ~ you-get -p mpv --debug http://www.douyu.tv/chuan967
you-get: version 0.4.486, a tiny downloader that scrapes the web.
you-get: ['http://www.douyu.tv/chuan967']
Traceback (most recent call last):
  File "/usr/local/Cellar/you-get/0.4.486/libexec/bin/you-get", line 9, in <module>
    load_entry_point('you-get==0.4.486', 'console_scripts', 'you-get')()
  File "/usr/local/Cellar/you-get/0.4.486/libexec/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/Cellar/you-get/0.4.486/libexec/lib/python3.5/site-packages/you_get/common.py", line 1328, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.486/libexec/lib/python3.5/site-packages/you_get/common.py", line 1241, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/Cellar/you-get/0.4.486/libexec/lib/python3.5/site-packages/you_get/common.py", line 1060, in download_main
    download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.486/libexec/lib/python3.5/site-packages/you_get/common.py", line 1321, in any_download
    m.download(url, **kwargs)
  File "/usr/local/Cellar/you-get/0.4.486/libexec/lib/python3.5/site-packages/you_get/extractors/douyutv.py", line 18, in douyutv_download
    server_status = data.get('error',0)
AttributeError: 'str' object has no attribute 'get'
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by cnbeining** [comment] 2016-07-23 07:39
Duplicate of #1299 .

**Closed by cnbeining** 2016-07-23 07:39 UTC
Labels: confirmed
