### ISSUE TITLE
iQiyi - Cannot download video from iQiyi

### ISSUE THREAD

**Issue by redstoneleo** [soimort/you-get#505] opened 2015-03-24 10:22 UTC
```
C:\Python34\Scripts>you-get 'http://www.iqiyi.com/dongman/20120531/8cfe3e9c25082
2b0.html?vfm=2008_aldbd&fm=ala'
Traceback (most recent call last):
  File "C:\Python34\Scripts\you-get-script.py", line 9, in <module>
    load_entry_point('you-get==0.3.32', 'console_scripts', 'you-get')()
  File "C:\Python34\lib\site-packages\you_get-0.3.32-py3.4.egg\you_get\__main__.
py", line 91, in main
    main()
  File "C:\Python34\lib\site-packages\you_get-0.3.32-py3.4.egg\you_get\common.py
", line 998, in main
    script_main('you-get', any_download, any_download_playlist)
  File "C:\Python34\lib\site-packages\you_get-0.3.32-py3.4.egg\you_get\common.py
", line 892, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only)
  File "C:\Python34\lib\site-packages\you_get-0.3.32-py3.4.egg\you_get\common.py
", line 784, in download_main
    download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get-0.3.32-py3.4.egg\you_get\common.py
", line 990, in any_download
    m, url = url_to_module(url)
  File "C:\Python34\lib\site-packages\you_get-0.3.32-py3.4.egg\you_get\common.py
", line 981, in url_to_module
    conn.request("HEAD", video_url)
  File "C:\Python34\lib\http\client.py", line 1090, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1128, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1086, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 924, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 859, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 836, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 491, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Python34\lib\socket.py", line 530, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed
'fm' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
```

**Comment by jackyzy823** [comment] 2015-03-24 15:40
$ you-get 'http://www.iqiyi.com/dongman/20120531/8cfe3e9c250822b0.html?vfm=2008_aldbd&fm=ala'
Video Site: iQIYI.com
Title:      犬夜叉第1集
Type:       Flash video (video/x-flv)
Size:       139.79 MiB (146579445 Bytes)

Downloading 犬夜叉第1集.flv ...
 24.0% ( 33.5/139.8MB) [==========                              ] 1/4^C% 

All right for me. Maybe for windows some problems occur when parsing arguments like "?vfm"
try to use url without useless url query : `http://www.iqiyi.com/dongman/20120531/8cfe3e9c25082
2b0.html `

**Comment by Elliotong** [comment] 2015-03-25 16:01
D:\Program Files\you-get-develop>python you-get 'http://v.youku.com/v_show/id_XO
Dg3OTYzMTU2.html'
Traceback (most recent call last):
  File "you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "D:\Program Files\you-get-develop\src\you_get\__main__.py", line 91, in m
ain
    main()
  File "D:\Program Files\you-get-develop\src\you_get\common.py", line 999, in ma
in
    script_main('you-get', any_download, any_download_playlist)
  File "D:\Program Files\you-get-develop\src\you_get\common.py", line 893, in sc
ript_main
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only)
  File "D:\Program Files\you-get-develop\src\you_get\common.py", line 785, in do
wnload_main
    download(url, **kwargs)
  File "D:\Program Files\you-get-develop\src\you_get\common.py", line 991, in an
y_download
    m, url = url_to_module(url)
  File "D:\Program Files\you-get-develop\src\you_get\common.py", line 982, in ur
l_to_module
    conn.request("HEAD", video_url)
  File "C:\Python34\lib\http\client.py", line 1088, in request
    self._send_request(method, url, body, headers)
  File "C:\Python34\lib\http\client.py", line 1126, in _send_request
    self.endheaders(body)
  File "C:\Python34\lib\http\client.py", line 1084, in endheaders
    self._send_output(message_body)
  File "C:\Python34\lib\http\client.py", line 922, in _send_output
    self.send(msg)
  File "C:\Python34\lib\http\client.py", line 857, in send
    self.connect()
  File "C:\Python34\lib\http\client.py", line 834, in connect
    self.timeout, self.source_address)
  File "C:\Python34\lib\socket.py", line 494, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Python34\lib\socket.py", line 533, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11004] getaddrinfo failed

**Comment by jackyzy823** [comment] 2015-03-25 16:33
python3 you-get 'http://v.youku.com/v_show/id_XODg3OTYzMTU2.html'
site:                优酷 (Youku)
title:               微软 Surface Pro 3 消费者报告 by FView
stream:
    - format:        hd3
      container:     flv
      video-profile: 1080P
      size:          455.4 MiB (477506778 bytes)
    # download-with: you-get --format=hd3 [URL]

Downloading 微软 Surface Pro 3 消费者报告 by FView.flv ...
  1.3% (  5.8/455.4MB) [=                                       ] 1/13^C% 


All right for me.Please check your network (overseas ip?) or network settings(seems like dns problem).

**Comment by Elliotong** [comment] 2015-03-29 07:45
@jackyzy823 thks

D:\Program Files\you-get>python you-get http://my.tv.sohu.com/us/248878311/79228
538.shtml
Traceback (most recent call last):
  File "you-get", line 19, in <module>
    you_get.main(repo_path=_filepath)
  File "D:\Program Files\you-get\src\you_get\__main__.py", line 91, in main
    main()
  File "D:\Program Files\you-get\src\you_get\common.py", line 999, in main
    script_main('you-get', any_download, any_download_playlist)
  File "D:\Program Files\you-get\src\you_get\common.py", line 893, in script_mai
n
    download_main(download, download_playlist, args, playlist, output_dir=output
_dir, merge=merge, info_only=info_only)
  File "D:\Program Files\you-get\src\you_get\common.py", line 785, in download_m
ain
    download(url, **kwargs)
  File "D:\Program Files\you-get\src\you_get\common.py", line 992, in any_downlo
ad
    m.download(url, **kwargs)
  File "D:\Program Files\you-get\src\you_get\extractors\sohu.py", line 55, in so
hu_download
    assert data['clipsURL'][0].endswith('.mp4')
AssertionError

**Comment by Hasset** [comment] 2015-05-18 08:54
```bash
$ you-get 'http://www.iqiyi.com/dongman/20120531/8cfe3e9c250822b0.html?vfm=2008_aldbd&fm=ala'
.Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/site-packages/you_get/__main__.py", line 91, in main
    main()
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 998, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 892, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 784, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 991, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get/extractors/iqiyi.py", line 71, in iqiyi_download
    title = info["data"]["vi"]["vn"]
KeyError: 'data'
```

```bash
you-get http://www.iqiyi.com/v_19rrnrlea0.html
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/site-packages/you_get/__main__.py", line 91, in main
    main()
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 998, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 892, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 784, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 991, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get/extractors/iqiyi.py", line 71, in iqiyi_download
    title = info["data"]["vi"]["vn"]
KeyError: 'data'
```

**Comment by jackyzy823** [comment] 2015-05-18 23:37
@Hasset Please try `git clone -b iqiyi-key-again https://github.com/jackyzy823/you-get/` this version before my PR merged into the upstream.

**Comment by Hasset** [comment] 2015-05-18 23:59
Hi @jackyzy823 , thanks for your advice. But I install the you-get through `pip3`. Could you tell me what can I do alternatively?

**Comment by jackyzy823** [comment] 2015-05-19 00:42
waiting for soimort  to make a new release.

**Comment by yan12125** [comment] 2015-05-19 05:03
@Hasset Try
```
pip3 install git+https://github.com/jackyzy823/you-get/@iqiyi-key-again
```

**Comment by Hasset** [comment] 2015-05-19 06:43
Hi @yan12125 

```bash
$ pip3 install git+https://github.com/jackyzy823/you-get/@iqiyi-key-again
Collecting git+https://github.com/jackyzy823/you-get/@iqiyi-key-again
  Cloning https://github.com/jackyzy823/you-get/ (to iqiyi-key-again) to /var/folders/ln/.../T/pip-x0oomui9-build
  Requirement already satisfied (use --upgrade to upgrade): you-get==0.3.32 from git+https://github.com/jackyzy823/you-get/@iqiyi-key-again in /usr/local/lib/python3.4/site-packages
$ you-get http://www.iqiyi.com/v_19rrnrlea0.html
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.4/site-packages/you_get/__main__.py", line 91, in main
    main()
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 998, in main
    script_main('you-get', any_download, any_download_playlist)
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 892, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only)
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 784, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get/common.py", line 991, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.4/site-packages/you_get/extractors/iqiyi.py", line 71, in iqiyi_download
    title = info["data"]["vi"]["vn"]
KeyError: 'data'
```

**Comment by yan12125** [comment] 2015-05-19 09:02
@Hasset I'm not sure what's the cause, but you may need to uninstall the existing version first.

**Comment by Hasset** [comment] 2015-05-19 09:21
@yan12125 Thank you for your reminder. It's solved by your version.

**Comment by RussianNeuroMancer** [comment] 2015-05-24 07:19
jackyzy823, thanks! Your branch works for me.

**Closed** 2015-06-09 12:37 UTC

**Comment by Hasset** [comment] 2015-06-13 01:55
new version still cannot do that now

**Comment by yan12125** [comment] 2015-06-13 02:36
It's a endless war. See #542

**Comment by viewbowl** [comment] 2016-02-27 12:09
You can use Allavsoft to download and iQIYI videos to any video format like MP4, MOV, AVCHD, MTS, M2TS, ASF, DV, AVI, WMV, VOB, MKV, FLV, etc.
