### ISSUE TITLE
Letv 获取不到url

### ISSUE THREAD

**Issue by hugecheng** [soimort/you-get#859] opened 2016-01-07 13:25 UTC
$ python you-get -d -u http://www.letv.com/ptv/vplay/23517204.html?ref=10000000
1
Current Video Supports:
        --format 350 <URL>
        --format 720p <URL>
        --format 1000 <URL>
        --format 1300 <URL>
        --format 1080p <URL>
Site:       LeTV.com
Title:      捉妖记
Type:       MPEG-4 video (video/mp4)
Size:       2565.67 MiB (2690297108 Bytes)

you-get: version 0.4.232, a tiny downloader that scrapes the web.
you-get: ['http://www.letv.com/ptv/vplay/23517204.html?ref=100000001']
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "e:\TPhone\you-get\you-get-service\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "e:\TPhone\you-get\you-get-service\you_get\common.py", line 1247, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "e:\TPhone\you-get\you-get-service\you_get\common.py", line 1161, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only,
json_output=json_output)
  File "e:\TPhone\you-get\you-get-service\you_get\common.py", line 1014, in download_main
    download(url, **kwargs)
  File "e:\TPhone\you-get\you-get-service\you_get\common.py", line 1239, in any_download
    m.download(url, **kwargs)
  File "e:\TPhone\you-get\you-get-service\you_get\extractors\letv.py", line 139, in letv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, info_only=info_only,**kwargs)
  File "e:\TPhone\you-get\you-get-service\you_get\extractors\letv.py", line 98, in letv_download_by_vid
    download_urls(urls, title, ext, size, output_dir=output_dir, merge=merge)
  File "e:\TPhone\you-get\you-get-service\you_get\common.py", line 659, in download_urls
    session['video_urls'] = urls
  File "c:\Users\bono\AppData\Local\Programs\Python\Python35\lib\site-packages\werkzeug\local.py", line 346, in __setite
m__
    self._get_current_object()[key] = value
  File "c:\Users\bono\AppData\Local\Programs\Python\Python35\lib\site-packages\werkzeug\local.py", line 302, in _get_cur
rent_object
    return self.__local()
  File "c:\Users\bono\AppData\Local\Programs\Python\Python35\lib\site-packages\flask\globals.py", line 20, in _lookup_re
q_object
    raise RuntimeError('working outside of request context')
RuntimeError: working outside of request context

**Comment by soimort** [comment] 2016-01-08 02:18
Duplicate of #801.

**Closed by soimort** 2016-01-08 02:18 UTC
