### ISSUE TITLE
爱课程网下载问题

### ISSUE THREAD

**Issue by fanweiya** [soimort/you-get#1477] opened 2016-10-25 02:42 UTC
@liushuyu  I can only download  15MB, Can you download the full video?thx~

> you-get http://www.icourses.cn/coursestatic/course_3622.html
> [WARNING] Switching to playlist mode!
> [WARNING] Failed to fetch the video file! Retrying...
> Site:       icourses.cn
> Title:      生物化学 模块一 第1单元 绪论
> Type:       Flash video (video/x-flv)
> Size:       138.1 MiB (144812622 Bytes)
> 
> Downloading 生物化学 模块一 第1单元 绪论.flv ...
> 10.9% ( 15.0/138.1MB) ├█████────────────────────────────────────┤[1/1]  119 kB/syou-get: [error] oops, something went wrong.
> you-get: don't panic, c'est la vie. please try the following steps:
> you-get:   (1) Rule out any network problem.
> you-get:   (2) Make sure you-get is up-to-date.
> you-get:   (3) Check if the issue is already known, on
> you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
> you-get:         https://github.com/soimort/you-get/issues
> you-get:   (4) Run the command with '--debug' option,
> you-get:       and report this issue with the full output.

**Comment by fanweiya** [comment] 2016-10-25 02:51
**debug**
> you-get -d http://www.icourses.cn/coursestatic/course_3622.html
> [DEBUG] get_content: http://www.icourses.cn/coursestatic/course_3622.html
> [WARNING] Switching to playlist mode!
> [DEBUG] get_content: http://www.icourses.cn/coursestatic/course_3622.html
> [DEBUG] get_content: http://www.icourses.cn/jpk/viewCharacterDetail.action?sectionId=51266&courseId=3622
> [DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=1305295&courseId=3622&firstShowFlag=1
> [DEBUG] Requesting video resource location...
> [DEBUG] The result was success
> [DEBUG] The encryption mode is in effect
> [DEBUG] Concat`ed URL: http://media1.icourses.cn:8080/process7/campus/processres/flv/2016/6/2/ff808081-5505e47e-0155-0f0b8bae-000a.flv?h=XivPXJhV_SEvngJIfTkC_w&start=0&r=1477363491&lv=150606-1&lt=10-25%2F10%3A45%3A19&ls=play&p=151020
> [WARNING] Failed to fetch the video file! Retrying...
> [DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=1305295&courseId=3622&firstShowFlag=1
> [DEBUG] Requesting video resource location...
> [DEBUG] The result was success
> [DEBUG] The encryption mode is in effect
> [DEBUG] Concat`ed URL: http://media1.icourses.cn:8080/process7/campus/processres/flv/2016/6/2/ff808081-5505e47e-0155-0f0b8bae-000a.flv?h=_FL49fHGtOC1Kzdz8LXmsg&start=0&r=1477363494&lv=150606-1&lt=10-25%2F10%3A45%3A22&ls=play&p=151020
> [WARNING] Failed to fetch the video file! Retrying...
> [DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=1305295&courseId=3622&firstShowFlag=1
> [DEBUG] Requesting video resource location...
> [DEBUG] The result was success
> [DEBUG] The encryption mode is in effect
> [DEBUG] Concat`ed URL: http://media1.icourses.cn:8080/process7/campus/processres/flv/2016/6/2/ff808081-5505e47e-0155-0f0b8bae-000a.flv?h=_0H1wG8zm9Wmq2N-4IcuHQ&start=0&r=1477363528&lv=150606-1&lt=10-25%2F10%3A45%3A26&ls=play&p=151020
> Site:       icourses.cn
> Title:      生物化学 模块一 第1单元 绪论
> Type:       Flash video (video/x-flv)
> Size:       138.1 MiB (144812622 Bytes)
> 
> Downloading 生物化学 模块一 第1单元 绪论.flv ...
>  0.0% (  0.0/138.1MB) ├─────────────────────────────────────────┤[1/1] you-get: version 0.4.555, a tiny downloader that scrapes the web.
> you-get: ['http://www.icourses.cn/coursestatic/course_3622.html']
> Traceback (most recent call last):
>   File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\runpy.py", line 184, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\fanweiya\AppData\Local\Programs\Python\Python35\Scripts\you-get.exe\__main__.py", line 9, in <module>
>   File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\__main__.py", line 92, in main
>     main(**kwargs)
>   File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1349, in main
>     script_main('you-get', any_download, any_download_playlist, **kwargs)
>   File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1262, in script_main
>     download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
>   File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1078, in download_main
>     download(url, **kwargs)
>   File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1342, in any_download
>     m.download(url, **kwargs)
>   File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\extractors\icourses.py", line 17, in icourses_download
>     url, info_only=info_only, **kwargs)
>   File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\extractors\icourses.py", line 60, in icourses_cn_url_parser
>     return icourses_playlist_download(url, **kwargs)
>   File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\extractors\icourses.py", line 50, in icourses_playlist_download
>     icourses_download(url=video_url, **kwargs)
>   File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\extractors\icourses.py", line 29, in icourses_download
>     total_size=size, output_dir=output_dir, refer=url, merge=merge, faker=True)
>   File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 729, in download_urls
>     url_save(url, output_filepath, bar, refer = refer, faker = faker, headers = headers)
>   File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 432, in url_save
>     file_size = url_size(url, faker = faker, headers = headers)
>   File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 346, in url_size
>     response = request.urlopen(request.Request(url, headers = fake_headers), None)
>   File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\urllib\request.py", line 163, in urlopen
>     return opener.open(url, data, timeout)
>   File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\urllib\request.py", line 472, in open
>     response = meth(req, response)
>   File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\urllib\request.py", line 582, in http_response
>     'http', request, response, code, msg, hdrs)
>   File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\urllib\request.py", line 510, in error
>     return self._call_chain(*args)
>   File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\urllib\request.py", line 444, in _call_chain
>     result = func(*args)
>   File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\urllib\request.py", line 590, in http_error_default
>     raise HTTPError(req.full_url, code, msg, hdrs, fp)
> urllib.error.HTTPError: HTTP Error 404: Not Found

**Comment by liushuyu** [comment] 2016-10-25 03:53
@fanweiya This should be a bit tricky to fix, maybe you need to spare me several days

**Comment by fanweiya** [comment] 2016-10-25 04:31
@liushuyu Well, actually it requires quite a bit of work and research

**Comment by liushuyu** [comment] 2016-10-25 20:30
@fanweiya Got fixed in #1472 together with #1478

**Comment by liushuyu** [comment] 2016-10-25 20:31
@fanweiya If it works please let me know

**Comment by fanweiya** [comment] 2016-10-26 02:19
@liushuyu  not work

```
you-get -d http://www.icourses.cn/coursestatic/course_3622.html
[DEBUG] get_content: http://www.icourses.cn/coursestatic/course_3622.html
[WARNING] Switching to playlist mode!
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://www.icourses.cn/coursestatic/course_3622.html']
Traceback (most recent call last):
  File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\fanweiya\AppData\Local\Programs\Python\Python35\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1390, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1302, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1118, in download_main
    download(url, **kwargs)
  File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1382, in any_download
    m.download(url, **kwargs)
  File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\extractors\icourses.py", line 19, in icourses_download
    real_url = icourses_parser.icourses_cn_url_parser(**kwargs)
  File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\extractors\icourses.py", line 70, in icourses_cn_url_parser
    return self.icourses_playlist_download(**kwargs)
  File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\extractors\icourses.py", line 46, in icourses_playlist_download
    html = get_content(url)
NameError: name 'url' is not defined
```

**Comment by liushuyu** [comment] 2016-10-26 02:36
My bad, just a typo, change `html = get_content(url)` to `html = get_content(self.url)` will do. I will fix this after finishing the class.

**Comment by liushuyu** [comment] 2016-10-26 04:17
@fanweiya I think this time it should work

**Comment by v1-hermit** [comment] 2016-10-26 05:47
still not work. Nothing I can get but a jpg file.
D:\you-get-develop>python you-get -d http://www.icourses.cn/coursestatic/course_3622.html
[DEBUG] get_content: http://www.icourses.cn/coursestatic/course_3622.html
Site:       icourses.cn
Title:      ff808081-3b65fbac-013b-6b39532f-1644
Type:       JPEG Image (image/jpeg)
Size:       0.01 MiB (6754 Bytes)

Downloading ff808081-3b65fbac-013b-6b39532f-1644.jpg ...
 100% (  0.0/  0.0MB) ├█████████████████████████████████████████┤[1/1]  811  B/s

**Comment by liushuyu** [comment] 2016-10-26 05:53
> still not work. I can get nothing but a jpg file.

You are not using my modified version my friend. You're using official `develop` branch. My changes haven't merged into official branch yet.

**Comment by liushuyu** [comment] 2016-10-26 05:54
@v1-hermit You need to manually clone & merge 2 versions: PR #1472 and PR #1478 to get it works

**Comment by liushuyu** [comment] 2016-10-26 06:00
And @v1-hermit be aware with some limitations listed in #1472 , sometimes it won't work due to some external uncontrollable reasons which I can do nothing about. 
FYI, there's a small reference on how to get not yet merged changes:

1. Download the following files (Remember to check if the files are tainted):
https://github.com/soimort/you-get/pull/1478.diff
https://github.com/soimort/you-get/pull/1472.diff 
2. Apply these changes by
```
git checkout -b icourses
git am <path/to/1478.diff> <path/to/1472.diff>
```

**Comment by fanweiya** [comment] 2016-10-26 10:03
@liushuyu still not work. 
```
you-get -d http://www.icourses.cn/coursestatic/course_3622.html
[DEBUG] get_content: http://www.icourses.cn/coursestatic/course_3622.html
[WARNING] Switching to playlist mode!
[DEBUG] get_content: http://www.icourses.cn/coursestatic/course_3622.html
[DEBUG] get_content: http://www.icourses.cn/jpk/viewCharacterDetail.action?sectionId=51266&courseId=3622
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://www.icourses.cn/coursestatic/course_3622.html']
Traceback (most recent call last):
  File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\fanweiya\AppData\Local\Programs\Python\Python35\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1400, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1313, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1129, in download_main
    download(url, **kwargs)
  File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\common.py", line 1393, in any_download
    m.download(url, **kwargs)
  File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\extractors\icourses.py", line 19, in icourses_download
    real_url = icourses_parser.icourses_cn_url_parser(**kwargs)
  File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\extractors\icourses.py", line 70, in icourses_cn_url_parser
    return self.icourses_playlist_download(**kwargs)
  File "c:\users\fanweiya\appdata\local\programs\python\python35\lib\site-packages\you_get\extractors\icourses.py", line 61, in icourses_playlist_download
    icourses_download(video_url, **kwargs)
TypeError: icourses_download() missing 1 required positional argument: 'info_only'
```

**Comment by NCACN** [comment] 2016-10-26 10:58
try: you-get -di http://www.icourses.cn/coursestatic/course_3622.html
but I still get error:
[DEBUG] get_content: http://www.icourses.cn/coursestatic/course_3622.html
Site:       icourses.cn
Title:      ff808081-3b65fbac-013b-6b39532f-1644
Type:       JPEG Image (image/jpeg)
Size:       0.01 MiB (6754 Bytes)

**Comment by zhangn1985** [comment] 2016-10-26 11:09
都是一些闭着眼睛的。。。

**Comment by NCACN** [comment] 2016-10-26 11:15
……
你这不是视频播放页面啊……

**Comment by v1-hermit** [comment] 2016-10-26 12:02
still not work..
`D:\you-get-develop>python you-get -d http://www.icourses.cn/coursestatic/course_3622.html
[DEBUG] get_content: http://www.icourses.cn/coursestatic/course_3622.html
[WARNING] Switching to playlist mode!
[DEBUG] get_content: http://www.icourses.cn/coursestatic/course_3622.html
[DEBUG] get_content: http://www.icourses.cn/jpk/viewCharacterDetail.action?sectionId=51266&courseId=3622
[DEBUG] get_content: http://www.icourses.cn/jpk/changeforVideo.action?resId=1305295&courseId=3622&firstShowFlag=1
[DEBUG] Requesting video resource location...
[DEBUG] The result was success
[DEBUG] The encryption mode is in effect
[DEBUG] Crafted URL: http://media1.icourses.cn:8080/process7/campus/processres/flv/2016/6/2/ff808081-5505e47e-0155-0f0b8bae-000a.flv?lt=10-26%2F19%3A55%3A01&start=0&lv=150606-1&h=-f8G0P8bKnUO8PnnOCZQH
A&ls=play&p=151020&r=1477483116
you-get: version 0.4.555, a tiny downloader that scrapes the web.
you-get: ['http://www.icourses.cn/coursestatic/course_3622.html']
Traceback (most recent call last):
  File "you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "D:\you-get-develop/src\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "D:\you-get-develop/src\you_get\common.py", line 1400, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "D:\you-get-develop/src\you_get\common.py", line 1313, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "D:\you-get-develop/src\you_get\common.py", line 1129, in download_main
    download(url, **kwargs)
  File "D:\you-get-develop/src\you_get\common.py", line 1393, in any_download
    m.download(url, **kwargs)
  File "D:\you-get-develop/src\you_get\extractors\icourses.py", line 19, in icourses_download
    real_url = icourses_parser.icourses_cn_url_parser(**kwargs)
  File "D:\you-get-develop/src\you_get\extractors\icourses.py", line 70, in icourses_cn_url_parser
    return self.icourses_playlist_download(**kwargs)
  File "D:\you-get-develop/src\you_get\extractors\icourses.py", line 61, in icourses_playlist_download
    icourses_download(video_url, **kwargs)
  File "D:\you-get-develop/src\you_get\extractors\icourses.py", line 31, in icourses_download
    print_info(site_info, title, type_, size)
UnboundLocalError: local variable 'type_' referenced before assignment`

**Comment by fanweiya** [comment] 2016-10-26 12:11
@NCACN 爱课程现在还未合并，没有在PIP上部署分发，你可以下载liushuyu的提交的PR，再进行测试

**Comment by liushuyu** [comment] 2016-10-26 19:55
I don't think it's my problem
This is the result from the computer from the lab of my university:
```
student_24@lab1_4:~/Downloads/you-get>./you-get  "http://www.icourses.cn/coursestatic/course_3622.html"
[WARNING] Switching to playlist mode!
Site:       icourses.cn
Title:      生物化学 模块一 第1单元 绪论
Type:       Flash video (video/x-flv)
Size:       138.1 MiB (144812622 Bytes)

Downloading 生物化学 模块一 第1单元 绪论.flv ...
 100% (138.1/138.1MB) ├█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████┤[1/1]   36 MB/s

Site:       icourses.cn
Title:      生物化学 模块一 第1单元 蛋白质的化学-1
Type:       Flash video (video/x-flv)
Size:       190.8 MiB (200064731 Bytes)

Downloading 生物化学 模块一 第1单元 蛋白质的化学-1.flv ...
 5.8% ( 11.0/190.8MB) ├████████─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┤[1/1]    5 MB/s^Cstudent24@lab1_4:~/Downloads/you-get>
```

**Comment by fanweiya** [comment] 2016-10-27 05:27
@soimort Wait for merge.

**Comment by v1-hermit** [comment] 2016-10-27 13:01
It worked once today,most of time not.Maybe some netwok reasons.Could you please work out this one @liushuyu #1283 ?

**Closed** 2016-11-04 16:17 UTC

**Comment by shigubuhua** [comment] 2016-12-05 04:59
@liushuyu Patch format detection failed.

**Comment by tengliu0929** [comment] 2017-09-10 03:49
git checkout -b icourses
git am <path/to/1478.diff> <path/to/1472.diff>
After I applied the upper command in the directory of you-get, I got a wrong message, Patch format detection failed, I am not familiar with git command, would anyone help? Thank you!

**Comment by rosynirvana** [comment] 2017-09-10 04:02
Message provided here is outdated
Now the develop branch support icourses.

**Comment by tengliu0929** [comment] 2017-09-10 04:09
Got it!thank you very much

**Comment by plsshutup** [comment] 2017-10-01 16:07
下载不了………………

>you-get -i http://www.icourses.cn/jpk/viewCharacterDetail.action?courseId=3008&
characId=20958
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
'characId' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
