### ISSUE TITLE
-x 代理问题

### ISSUE THREAD

**Issue by zouhua** [soimort/you-get#1096] opened 2016-05-02 09:46 UTC
> [root@vagrant-centos65 you-get]# ./you-get -x 127.0.0.1:1080 'https://www.youtube.com/watch?v=CEXfqzzl6Jg'
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.

火狐用代理127.0.0.1 1080 socket 是能访问youtube 的

**Comment by zouhua** [comment] 2016-05-02 09:49
> [root@vagrant-centos65 you-get]# ./you-get --debug  -x 127.0.0.1:1080 'https://www.youtube.com/watch?v=CEXfqzzl6Jg'
[DEBUG] get_content: https://www.youtube.com/get_video_info?video_id=CEXfqzzl6Jg
you-get: version 0.4.365, a tiny downloader that scrapes the web.
you-get: ['https://www.youtube.com/watch?v=CEXfqzzl6Jg']
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/urllib/request.py", line 1240, in do_open
    h.request(req.get_method(), req.selector, req.data, headers)
  File "/usr/local/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/local/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/local/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/local/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/usr/local/lib/python3.5/http/client.py", line 1229, in connect
    super().connect()
  File "/usr/local/lib/python3.5/http/client.py", line 826, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/local/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/usr/local/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "./src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "./src/you_get/common.py", line 1274, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "./src/you_get/common.py", line 1187, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "./src/you_get/common.py", line 1030, in download_main
    download(url, **kwargs)
  File "./src/you_get/common.py", line 1267, in any_download
    m.download(url, **kwargs)
  File "./src/you_get/extractor.py", line 40, in download_by_url
    self.prepare(**kwargs)
  File "./src/you_get/extractors/youtube.py", line 143, in prepare
    video_info = parse.parse_qs(get_content('https://www.youtube.com/get_video_info?video_id={}'.format(self.vid)))
  File "./src/you_get/common.py", line 308, in get_content
    response = request.urlopen(req)
  File "/usr/local/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/local/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.5/urllib/request.py", line 1283, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/local/lib/python3.5/urllib/request.py", line 1242, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 111] Connection refused>

@soimort-bot

**Comment by soimort** [comment] 2016-05-02 11:04
`-x`仅支持HTTP proxy，SOCKS请用proxychains。

Duplicate of #1046/

**Closed by soimort** 2016-05-02 11:04 UTC
Labels: invalid
