### ISSUE TITLE
请在ffmpeg调用命令中添加'-safe 0'来避免'Unsafe file name'问题

### ISSUE THREAD

**Issue by petronny** [soimort/you-get#1023] opened 2016-04-04 08:25 UTC
今天拖名字带奇怪字符的视频时遇到的
Archlinux x86_64
you-get-git 0.4.365.20160331.1219-1(就是3月31日的版本)
ffmpeg 1:3.0.1-1
然后会无法合并文件

解决办法如题
具体的说是加在'-f concat'后面就好了

参见https://www.ffmpeg.org/ffmpeg-formats.html#toc-Options

**Comment by soimort** [comment] 2016-04-04 21:16
Thanks for the report. (confirmed duplicate of #1018)

I don't know why they are making sudden changes like this, without even mentioning it in their release notes:
https://github.com/FFmpeg/FFmpeg/commit/689211d5727231c3fe92762d224dbadebdbf4e30

(Normally you would not expect such a compatibility issue during the version 3.0.0 to 3.0.1 cycle, but it just happened. :disappointed: )

**Closed** 2016-04-04 22:48 UTC
