### ISSUE TITLE
腾讯视频下载有问题

### ISSUE THREAD

**Issue by hugecheng** [soimort/you-get#840] opened 2015-12-29 09:29 UTC
C:\Users\XXX\PycharmProjects\you-get>python you-get --debug http://v.qq.com/cover/h/hie1zs7llxal83g.html
you-get: version 0.4.217, a tiny downloader that scrapes the web.
you-get: ['http://v.qq.com/cover/h/hie1zs7llxal83g.html']
Traceback (most recent call last):
File "you-get", line 11, in 
you_get.main(repo_path=filepath)
File "src\you_get__main_.py", line 92, in main
main(*kwargs)
File "src\you_get\common.py", line 1229, in main
script_main('you-get', any_download, any_download_playlist, *kwargs)
File "src\you_get\common.py", line 1150, in script_main
download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only,
json_output=json_output)
File "src\you_get\common.py", line 1003, in download_main
download(url, *kwargs)
File "src\you_get\common.py", line 1222, in any_download
m.download(url, *kwargs)
File "src\you_get\extractors\qq.py", line 23, in qq_download
qq_download_by_vid(vid, title, output_dir, merge, info_only)
File "src\you_get\extractors\qq.py", line 11, in qq_download_by_vid
url = output_json['vd']['vi'][0]['url']
KeyError: 'vd'

单步跟踪看到：
'QZOutputJson={"ch":"-1","em":83,"msg":"user haven\'t pay or log in","s":"f"};'

要先登录？

**Comment by soimort** [comment] 2015-12-29 15:30
Duplicate of #663.

**Closed** 2015-12-31 14:38 UTC
Labels: duplicate
