### ISSUE TITLE
斗鱼的key好像失效了

### ISSUE THREAD

**Issue by lexcn** [soimort/you-get#1719] opened 2017-02-28 11:08 UTC
无法计算出可用的sign值，youtube-dl使用的是同一个key也出现了同样的问题

- [x] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [x] Your `you-get` is up-to-date.
- [x] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [x] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [x] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[[DEBUG] get_content: http://www.douyu.com/27836
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=27836
sign=7d7f30145123ef16188c61edcc308894&tt=24804645&cdn=ws&rate=0&did=6F18D534AFF946A8ADAB7C9CE95B78AF
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['https://www.douyu.com/27836']
Traceback (most recent call last):
  File "d:\program files\anaconda3\envs\py3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\anaconda3\envs\py3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Anaconda3\envs\py3\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "d:\program files\anaconda3\envs\py3\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "d:\program files\anaconda3\envs\py3\lib\site-packages\you_get\common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "d:\program files\anaconda3\envs\py3\lib\site-packages\you_get\common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "d:\program files\anaconda3\envs\py3\lib\site-packages\you_get\common.py", line 1136, in download_main
    download(url, **kwargs)
  File "d:\program files\anaconda3\envs\py3\lib\site-packages\you_get\common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "d:\program files\anaconda3\envs\py3\lib\site-packages\you_get\extractors\douyutv.py", line 41, in douyutv_download
    with urllib.request.urlopen(req) as response:
  File "d:\program files\anaconda3\envs\py3\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "d:\program files\anaconda3\envs\py3\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "d:\program files\anaconda3\envs\py3\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\program files\anaconda3\envs\py3\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "d:\program files\anaconda3\envs\py3\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "d:\program files\anaconda3\envs\py3\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
- [x] 您的`you-get`为最新版.
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
- [x] 本问题确实关于`you-get`, 而不是其他项目.

请使用`--debug`运行，并将输出粘贴在下面:

```
[[DEBUG] get_content: http://www.douyu.com/27836
[DEBUG] get_content: http://m.douyu.com/html5/live?roomId=27836
sign=7d7f30145123ef16188c61edcc308894&tt=24804645&cdn=ws&rate=0&did=6F18D534AFF946A8ADAB7C9CE95B78AF
you-get: version 0.4.652, a tiny downloader that scrapes the web.
you-get: ['https://www.douyu.com/27836']
Traceback (most recent call last):
  File "d:\program files\anaconda3\envs\py3\lib\runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\program files\anaconda3\envs\py3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files\Anaconda3\envs\py3\Scripts\you-get.exe\__main__.py", line 9, in <module>
  File "d:\program files\anaconda3\envs\py3\lib\site-packages\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "d:\program files\anaconda3\envs\py3\lib\site-packages\you_get\common.py", line 1407, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "d:\program files\anaconda3\envs\py3\lib\site-packages\you_get\common.py", line 1320, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "d:\program files\anaconda3\envs\py3\lib\site-packages\you_get\common.py", line 1136, in download_main
    download(url, **kwargs)
  File "d:\program files\anaconda3\envs\py3\lib\site-packages\you_get\common.py", line 1400, in any_download
    m.download(url, **kwargs)
  File "d:\program files\anaconda3\envs\py3\lib\site-packages\you_get\extractors\douyutv.py", line 41, in douyutv_download
    with urllib.request.urlopen(req) as response:
  File "d:\program files\anaconda3\envs\py3\lib\urllib\request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "d:\program files\anaconda3\envs\py3\lib\urllib\request.py", line 472, in open
    response = meth(req, response)
  File "d:\program files\anaconda3\envs\py3\lib\urllib\request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "d:\program files\anaconda3\envs\py3\lib\urllib\request.py", line 510, in error
    return self._call_chain(*args)
  File "d:\program files\anaconda3\envs\py3\lib\urllib\request.py", line 444, in _call_chain
    result = func(*args)
  File "d:\program files\anaconda3\envs\py3\lib\urllib\request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden]
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:

> [您的内容]
> [舔 :icecream:!]

**Comment by chacha1024** [comment] 2017-02-28 11:18
伦伦世界第一可爱

**Comment by cnbeining** [comment] 2017-03-02 16:19
Duplicate of #1720 .

**Closed by cnbeining** 2017-03-02 16:19 UTC
Labels: confirmed
