### ISSUE TITLE
腾讯视频挂了

### ISSUE THREAD

**Issue by redstoneleo** [soimort/you-get#764] opened 2015-11-13 04:38 UTC
you-get -u --debug http://v.qq.com/cover/s/svchbf3vtur43r6.html

you-get: version 0.4.125, a tiny downloader that scrapes the web.
you-get: ['http://v.qq.com/cover/s/svchbf3vtur43r6.html']
Traceback (most recent call last):
  File "C:\Python34\Scripts\you-get-script.py", line 9, in <module>
    load_entry_point('you-get==0.4.125', 'console_scripts', 'you-get')()
  File "C:\Python34\lib\site-packages\you_get-0.4.125-py3.4.egg\you_get\__main__.py", line 92, in main
    main(**kwargs)
  File "C:\Python34\lib\site-packages\you_get-0.4.125-py3.4.egg\you_get\common.py", line 1213, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "C:\Python34\lib\site-packages\you_get-0.4.125-py3.4.egg\you_get\common.py", line 1134, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "C:\Python34\lib\site-packages\you_get-0.4.125-py3.4.egg\you_get\common.py", line 987, in download_main
    download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get-0.4.125-py3.4.egg\you_get\common.py", line 1206, in any_download
    m.download(url, **kwargs)
  File "C:\Python34\lib\site-packages\you_get-0.4.125-py3.4.egg\you_get\extractors\qq.py", line 23, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "C:\Python34\lib\site-packages\you_get-0.4.125-py3.4.egg\you_get\extractors\qq.py", line 11, in qq_download_by_vid
    url = output_json['vd']['vi'][0]['url']
KeyError: 'vd'
Traceback (most recent call last):
  File "E:\360云盘\编程\Python\qiyi.py", line 19, in <module>
    "http://v.qq.com/cover/s/svchbf3vtur43r6.html"])
  File "C:\Python34\lib\subprocess.py", line 620, in check_output
    raise CalledProcessError(retcode, process.args, output=output)
subprocess.CalledProcessError: Command '['C:\\Python34\\Scripts\\you-get.exe', '-u', '--debug', 'http://v.qq.com/cover/s/svchbf3vtur43r6.html']' returned non-zero exit status 1

**Comment by soimort** [comment] 2015-11-13 18:06
Duplicate of #663.

**Closed by soimort** 2015-11-13 18:06 UTC
