### ISSUE TITLE
letv 乐视合并视频问题

### ISSUE THREAD

**Issue by jasonham** [soimort/you-get#829] opened 2015-12-23 20:24 UTC
you-get -d --format 1300 http://www.letv.com/ptv/vplay/24135799.html

Merging video parts... you-get: version 0.4.217, a tiny downloader that scrapes the web.
you-get: ['http://www.letv.com/ptv/vplay/24135799.html']
Traceback (most recent call last):
  File "/usr/local/var/pyenv/versions/3.5.1/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/you_get/common.py", line 1229, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/you_get/common.py", line 1145, in script_main
    download_main(download, download_playlist, args, playlist, stream_id=stream_id, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/you_get/common.py", line 1003, in download_main
    download(url, **kwargs)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/you_get/common.py", line 1222, in any_download
    m.download(url, **kwargs)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/you_get/extractors/letv.py", line 139, in letv_download
    letv_download_by_vid(vid, title=title, output_dir=output_dir, merge=merge, info_only=info_only,**kwargs)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/you_get/extractors/letv.py", line 98, in letv_download_by_vid
    download_urls(urls, title, ext, size, output_dir=output_dir, merge=merge)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/you_get/common.py", line 735, in download_urls
    ffmpeg_concat_mp4_to_mp4(parts, output_filepath)
  File "/usr/local/var/pyenv/versions/3.5.1/lib/python3.5/site-packages/you_get/processor/ffmpeg.py", line 177, in ffmpeg_concat_mp4_to_mp4
    raise
RuntimeError: No active exception to reraise

可以生成 『芈月传20.mp4.txt』和一个只有30K 的芈月传20.mp4

手动合并 
ffmpeg -f concat -i 芈月传20.mp4.txt -c copy 芈月传20.mp4 
提示
[mp4 @ 0x7f801902d600] Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)
av_interleaved_write_frame(): Operation not permitted
[mp4 @ 0x7f801902d600] Malformed AAC bitstream detected: use the audio bitstream filter 'aac_adtstoasc' to fix it ('-bsf:a aac_adtstoasc' option with ffmpeg)

改手动合并：
ffmpeg -f concat -i 芈月传20.mp4.txt -c copy -bsf:a aac_adtstoasc 芈月传20.mp4
生成了
SIZE为278614887 的芈月传20.mp4
粗看一下没明显问题，但原视频you-get -i 时看到的SIZE应该为 278.84 MiB (292382112 Bytes)
不知道有没有影响，怎么才能自己合并视频？
还有一并问一下，raspberry pi2的raspbian软件源中的ffmpeg 只有0.8.17，要怎么才能手动合并视频？

**Comment by cnbeining** [comment] 2015-12-25 05:42
Duplicate of #813 .

**Comment by cnbeining** [comment] 2015-12-25 05:42
自己编译个ffmpeg吧，这么古老的版本估计连文档都没了。

**Comment by xyuanmu** [comment] 2016-01-05 07:51
你还有生成txt，我这里连txt都没生成，要怎么用ffmpeg合并啊？是不是把所有视频的文件名写入一个txt里就行啊？

**Comment by jasonham** [comment] 2016-01-05 11:48
有格式的，例如
# this is a comment
file '/path/to/file1'
file '/path/to/file2'
file '/path/to/file3'
具体见https://trac.ffmpeg.org/wiki/Concatenate

**Comment by xyuanmu** [comment] 2016-01-05 13:49
@jasonham 谢谢，我更新了ffmpeg现在能正常合并了。

**Comment by cnbeining** [comment] 2016-01-05 14:36
请关闭issue，如果问题已经解决，谢谢。

**Closed** 2016-01-06 16:04 UTC
Labels: duplicate
