### ISSUE TITLE
you-get播放acfun失败

### ISSUE THREAD

**Issue by wyssurvivor** [soimort/you-get#855] opened 2016-01-04 17:41 UTC
更新了you－get插件随便打开一个acfun视频
http://www.acfun.tv/v/ac2433742
失败

> 视频解析失败，返回信息：
> you-get: [error] oops, something went wrong.
> you-get: don't panic, c'est la vie. please try the following steps:
> you-get:   (1) Rule out any network problem.
> you-get:   (2) Make sure you-get is up-to-date.
> you-get:   (3) Check if the issue is already known, on
> you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
> you-get:         https://github.com/soimort/you-get/issues
> you-get:   (4) Run the command with '--debug' option,
> you-get:       and report this issue with the full output.

**Comment by cnbeining** [comment] 2016-01-04 19:31
Duplicate of #776 . 

Do not expect a quick fix in the near future...

**Closed** 2016-01-06 16:04 UTC
