### ISSUE TITLE
Is there a way of renaming the file downloaded ?

### ISSUE THREAD

**Issue by caiqiqi** [soimort/you-get#722] opened 2015-10-21 11:19 UTC
Is there a way of renaming the file downloaded ?Because the filename consists of many spaces and I could not operate on that file well.
![issue](https://cloud.githubusercontent.com/assets/8278315/10635071/a7e89976-7828-11e5-9d79-46ba1d2cd38c.PNG)

**Comment by soimort** [comment] 2015-10-21 15:04
Duplicate of #425.

**Closed** 2015-10-21 18:36 UTC
