### ISSUE TITLE
这个可能跟1211问题有关吧。。。I think this question and #1211 are closely relate.

### ISSUE THREAD

**Issue by cybmp3** [soimort/you-get#1245] opened 2016-07-01 16:01 UTC
Please make sure these boxes are checked before submitting your issue – thank you!

- [ ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
sure! 
http://www.iqiyi.com/v_19rrkxmiss.html
- [ ] Your `you-get` is up-to-date.
sure! download by
wget https://github.com/soimort/you-get/archive/develop.zip(at 20160702 BEIJING TIME 00;00)
- [ ] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
sure!
- [ ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.

- [ ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
./you-get --debug http://www.iqiyi.com/v_19rrkxmiss.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/453406400/778e9e5286f2ca6a94d8b5da0062f978/?t=1467388639069&sc=bbce6d02a205c40ff8ba985cf6f4d422&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: version 0.4.455, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rrkxmiss.html']
Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/root/you-get-develop/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/root/you-get-develop/src/you_get/common.py", line 1328, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/root/you-get-develop/src/you_get/common.py", line 1241, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/root/you-get-develop/src/you_get/common.py", line 1060, in download_main
    download(url, **kwargs)
  File "/root/you-get-develop/src/you_get/common.py", line 1321, in any_download
    m.download(url, **kwargs)
  File "/root/you-get-develop/src/you_get/extractor.py", line 40, in download_by_url
    self.prepare(**kwargs)
  File "/root/you-get-develop/src/you_get/extractors/iqiyi.py", line 153, in prepare
    if 18 in info['data']['ctl']['vip']['bids']:
KeyError: 'ctl'

```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

汉语翻译最终日期：2016年02月26日

在提交前，请确保您已经检查了以下内容!

- [x] 你可以在浏览器或移动端中观看视频，但不能使用`you-get`下载.
当然啊！
http://www.iqiyi.com/v_19rrkxmiss.html
- [x] 您的`you-get`为最新版.
当然啊！
wget https://github.com/soimort/you-get/archive/develop.zip(用WGET在北京时间20160702 00:000)
- [x] 我已经阅读并按 <https://github.com/soimort/you-get/wiki/FAQ> 中的指引进行了操作.
当然啊！
- [x] 您的问题没有在<https://github.com/soimort/you-get/issues> , <https://github.com/soimort/you-get/wiki/FAQ> 或 <https://github.com/soimort/you-get/wiki/Known-Bugs> 报告，否则请在原有issue下报告.
当然啊！
- [x] 本问题确实关于`you-get`, 而不是其他项目.
当然啊！
请使用`--debug`运行，并将输出粘贴在下面:

```
./you-get --debug http://www.iqiyi.com/v_19rrkxmiss.html
[DEBUG] get_content: http://cache.m.iqiyi.com/tmts/453406400/778e9e5286f2ca6a94d8b5da0062f978/?t=1467388639069&sc=bbce6d02a205c40ff8ba985cf6f4d422&src=76f90cbd92f94a2e925d83e8ccd22cb7
you-get: version 0.4.455, a tiny downloader that scrapes the web.
you-get: ['http://www.iqiyi.com/v_19rrkxmiss.html']
Traceback (most recent call last):
  File "./you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/root/you-get-develop/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/root/you-get-develop/src/you_get/common.py", line 1328, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/root/you-get-develop/src/you_get/common.py", line 1241, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/root/you-get-develop/src/you_get/common.py", line 1060, in download_main
    download(url, **kwargs)
  File "/root/you-get-develop/src/you_get/common.py", line 1321, in any_download
    m.download(url, **kwargs)
  File "/root/you-get-develop/src/you_get/extractor.py", line 40, in download_by_url
    self.prepare(**kwargs)
  File "/root/you-get-develop/src/you_get/extractors/iqiyi.py", line 153, in prepare
    if 18 in info['data']['ctl']['vip']['bids']:
KeyError: 'ctl'
```

如果您有其他附言，例如问题只在某个视频发生，或者是一般性讨论或者提出新功能，请在下面添加;或者您可以卖个萌:
蛐蛐个蛐
> [您的内容]
> [舔 :icecream:!]

**Comment by soimort** [comment] 2016-07-01 16:06
Duplicate of #1228.

**Closed by soimort** 2016-07-01 16:06 UTC
Labels: confirmed
