### ISSUE TITLE
QQ download error

### ISSUE THREAD

**Issue by lucifekit** [soimort/you-get#1623] opened 2017-01-16 09:32 UTC
Please make sure these boxes are checked before submitting your issue – thank you!

- [ X] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [ X] Your `you-get` is up-to-date.
- [ X] I have read <https://github.com/soimort/you-get/wiki/FAQ> and tried to do so.
- [ X] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or  <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [ X] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:
you-get --debug  -u "https://v.qq.com/x/cover/1eyf4xyyez4p76n/t0363rio9ln.html"
```
you-get --debug  -u "https://v.qq.com/x/cover/1eyf4xyyez4p76n/t0363rio9ln.html"
you-get: version 0.4.626, a tiny downloader that scrapes the web.
you-get: ['https://v.qq.com/x/cover/1eyf4xyyez4p76n/t0363rio9ln.html']
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1410, in main
  File "src\you_get\common.py", line 1323, in script_main
  File "src\you_get\common.py", line 1139, in download_main
  File "src\you_get\common.py", line 1403, in any_download
  File "src\you_get\extractors\qq.py", line 111, in qq_download
  File "src\you_get\extractors\qq.py", line 55, in qq_download_by_vid
UnboundLocalError: local variable 'ext' referenced before assignment
you-get returned -1
```

**Comment by soimort** [comment] 2017-01-16 22:13
Duplicate of #1570.

**Closed by soimort** 2017-01-16 22:13 UTC
Labels: duplicate
