### ISSUE TITLE
failed when using https with youtube

### ISSUE THREAD

**Issue by tianyaqu** [soimort/you-get#1024] opened 2016-04-04 08:42 UTC
commands like you-get -x 127.0.0.1:8087 'https://www.youtube.com/watch?v=jNQXAC9IVRw' will fail,below is the debug message,the proxy is in good condition.
```
you-get: version 0.4.365, a tiny downloader that scrapes the web.
you-get: ["'https://www.youtube.com/watch?v=jNQXAC9IVRw'"]
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "src\you_get\__main__.py", line 92, in main
  File "src\you_get\common.py", line 1274, in main
  File "src\you_get\common.py", line 1187, in script_main
  File "src\you_get\common.py", line 1030, in download_main
  File "src\you_get\common.py", line 1266, in any_download
  File "src\you_get\common.py", line 1257, in url_to_module
  File "http\client.py", line 1083, in request
  File "http\client.py", line 1128, in _send_request
  File "http\client.py", line 1079, in endheaders
  File "http\client.py", line 911, in _send_output
  File "http\client.py", line 854, in send
  File "http\client.py", line 826, in connect
  File "socket.py", line 689, in create_connection
  File "socket.py", line 728, in getaddrinfo
socket.gaierror: [Errno 11001] getaddrinfo failed
you-get returned -1
```
As I turn to  another downloader  'youtube-dl',which unfortunately leads to a ssl error:
```
Unable to download webpage: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)> (caused by URLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)'),))
```
After add the no-check-certificate option to supress the https certificate validation,youtube-dl downloads sucessfully.

Maybe that's the reason,could you pls add a 'no-check-certificate' option like youtube-dl?

**Comment by soimort** [comment] 2016-04-06 18:20
Duplicate of #946.

**Closed** 2016-04-07 10:29 UTC
Labels: duplicate
