### ISSUE TITLE
[YOUKU]使徒行者只能下载5分钟左右的片段

### ISSUE THREAD

**Issue by westspy** [soimort/you-get#1319] opened 2016-07-31 07:17 UTC
MacBook-Pro:you-get-git westspy$ python3 you-get http://v.youku.com/v_show/id_XNzYxNzM0MDk2
you-get: [Error] HTTP Error 404: Not Found
site:                优酷 (Youku)
title:               使徒行者 01
stream:
    - format:        hd2
      container:     flv
      video-profile: 超清
      size:          377.2 MiB (395488235 bytes)
    # download-with: you-get --format=hd2 [URL]

audio-languages:
    - lang:          国语
      download-url:  http://v.youku.com/v_show/id_XNzYxNzM0MDk2

    - lang:          粤语
      download-url:  http://v.youku.com/v_show/id_XNzYxNzM4MDI4

Downloading 使徒行者 01.flv ...
14.1% ( 53.1/377.2MB) ├██████───────────────────────────────────┤[2/2]    7 MB/s
Merging video parts... Merged into 使徒行者 01.mp4

**Comment by jkng** [comment] 2016-07-31 23:19
双语的好像不能

**Comment by soimort** [comment] 2016-08-03 12:48
Duplicate of #1249

**Closed by soimort** 2016-08-03 12:48 UTC
