### ISSUE TITLE
爱奇艺视频下载解析后为什么是广告宣传片

### ISSUE THREAD

**Issue by dxg74120** [soimort/you-get#1220] opened 2016-06-22 14:50 UTC
$ you-get http://www.iqiyi.com/w_19rti6iegp.html
site:                爱奇艺 (Iqiyi)
title:               广告宣传片
stream:
    - format:        suprt-high
      container:     f4v
      video-profile: 超高清
      size:          16.4 MiB (17190194 bytes)
    # download-with: you-get --format=suprt-high [URL]

Downloading 广告宣传片.f4v ...
 4.6% (  0.8/ 16.4MB) ├██───────────────────────────────────────┤[1/1]    4 MB/s

**Comment by soimort** [comment] 2016-06-22 15:01
Duplicate of #1211.

**Closed** 2016-06-22 15:00 UTC
