### ISSUE TITLE
Downloading Youku VIP videos with cookies stuck at recv_into()

### ISSUE THREAD

**Issue by pxia** [soimort/you-get#928] opened 2016-02-21 04:42 UTC
```
$ you-get -c cookies.txt -d http://v.youku.com/v_show/id_XMTQ2NTI2NjQ3Ng\=\=.html\#paction
Traceback (most recent call last):
  File "/usr/local/bin/you-get", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/site-packages/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1250, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1171, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1019, in download_main
    download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 1243, in any_download
    m.download(url, **kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractor.py", line 48, in download_by_url
    self.extract(**kwargs)
  File "/usr/local/lib/python3.5/site-packages/you_get/extractors/youku.py", line 279, in extract
    ksegs += [i['server'] for i in json.loads(get_content(u))]
  File "/usr/local/lib/python3.5/site-packages/you_get/common.py", line 298, in get_content
    response = request.urlopen(req)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 465, in open
    response = self._open(req, data)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 483, in _open
    '_open', req)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 443, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1268, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/urllib/request.py", line 1243, in do_open
    r = h.getresponse()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1174, in getresponse
    response.begin()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 243, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
```

The cookies file is generated by the Chrome extension [cookies.txt](https://chrome.google.com/webstore/detail/njabckikapfpffapmjgojcnbfjonfjfg) after I login to youku with a vip account.

**Comment by soimort** [comment] 2016-02-21 05:18
Unfortunately I'm not able to look into this issue myself. You may try again with Firefox cookies, if you can.

Could anyone who has a Youku VIP account confirm this?

**Comment by soimort** [comment] 2016-02-27 15:19
It seems `self._sock.recv_into(b)` is a socket timeout which is usually caused by bad network / server status, rather than a general `you-get` issue. Please confirm if this issue still persists, or we may close it after a few days.

**Comment by pxia** [comment] 2016-02-29 09:35
I can now successfully download videos (again) using this method without changing anything. It seems like a a either a issue either of the network or the youku server of the time.

**Comment by soimort** [comment] 2016-02-29 13:39
Nice to see it works for you. Closing.

**Closed by soimort** 2016-02-29 13:39 UTC
