### ISSUE TITLE
Downloading Issue with v.qq.com

### ISSUE THREAD

**Issue by renuka25165** [soimort/you-get#945] opened 2016-03-03 10:45 UTC
Please make sure these boxes are checked before submitting your issue – thank you!

- [Yes ] You can actually watch the video in your browser or mobile application, but not download them with `you-get`.
- [Yes ] Your `you-get` is up-to-date.
- [Yes ] The issue is not yet reported on <https://github.com/soimort/you-get/issues> or <https://github.com/soimort/you-get/wiki/Known-Bugs>. If so, please add your comments under the existing issue.
- [Yes ] The issue (or question) is really about `you-get`, not about some other code or project.

Run the command with the `--debug` option, and paste the full output inside the fences:

```
[C:\Users\jaimin26783>you-get http://v.qq.com/prev/r/rag1eryxpr49pe3.html?vid=v0016tisa69 --debug
you-get: [error] oops, something went wrong.
you-get: don't panic, c'est la vie. please try the following steps:
you-get:   (1) Rule out any network problem.
you-get:   (2) Make sure you-get is up-to-date.
you-get:   (3) Check if the issue is already known, on
you-get:         https://github.com/soimort/you-get/wiki/Known-Bugs
you-get:         https://github.com/soimort/you-get/issues
you-get:   (4) Run the command with '--debug' option,
you-get:       and report this issue with the full output.
]
```

If there's anything else you would like to say (e.g. in case your issue is not about downloading a specific video; it might as well be a general discussion or proposal for a new feature), fill in the box below; otherwise, you may want to post an emoji or meme instead:

> [WRITE SOMETHING]
> [OR HAVE SOME :icecream:!]

**Comment by soimort** [comment] 2016-03-03 12:13
You'll have to put `--debug` before the URL.

```console
$ you-get --debug http://v.qq.com/prev/r/rag1eryxpr49pe3.html\?vid\=v0016tisa69        
you-get: version 0.4.312, a tiny downloader that scrapes the web.
you-get: ['http://v.qq.com/prev/r/rag1eryxpr49pe3.html?vid=v0016tisa69']
Traceback (most recent call last):
  File "/home/soimort/Projects/you-get/you-get", line 11, in <module>
    you_get.main(repo_path=_filepath)
  File "/home/soimort/Projects/you-get/src/you_get/__main__.py", line 92, in main
    main(**kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1250, in main
    script_main('you-get', any_download, any_download_playlist, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1171, in script_main
    download_main(download, download_playlist, args, playlist, output_dir=output_dir, merge=merge, info_only=info_only, json_output=json_output, caption=caption)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1019, in download_main
    download(url, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/common.py", line 1243, in any_download
    m.download(url, **kwargs)
  File "/home/soimort/Projects/you-get/src/you_get/extractors/qq.py", line 33, in qq_download
    qq_download_by_vid(vid, title, output_dir, merge, info_only)
  File "/home/soimort/Projects/you-get/src/you_get/extractors/qq.py", line 11, in qq_download_by_vid
    url = output_json['vl']['vi'][0]['ul']['ui'][0]['url']
KeyError: 'vl'
```

Probably a duplicate of #663.

**Comment by renuka25165** [comment] 2016-03-04 06:39
Its in Chinese. how am i able to download the video?

**Comment by soimort** [comment] 2016-03-05 04:27
@renuka25165 Unfortunately we'll have to wait until #663 is resolved.

Certain types of videos on qq.com (like this one, and the one in #663) are not yet supported by `you-get` for now.

**Comment by soimort** [comment] 2016-03-10 20:43
Can't reproduce on the latest version of `you-get`.

```console
$ you-get -di 'http://v.qq.com/prev/r/rag1eryxpr49pe3.html?vid=v0016tisa69'
Site:       QQ.com
Title:      《爱情麻辣烫之情定终身》终极版预告片
Type:       MPEG-4 video (video/mp4)
Size:       5.27 MiB (5522888 Bytes)
```

**Closed by soimort** 2016-03-10 20:43 UTC
Labels: duplicate
